### ISSUE TITLE
Subscription order, trial helper

### ISSUE THREAD

**Issue by saas786** [Automattic/woocommerce-subscriptions-core#107]
I am exporting data from "WooCommerce" to "ChartMogul", and it accepts two types of line items:
a) One Time
b) Subscription

None subscription orders are straight forward "One Time"
Subscription orders, specially parent orders need to be tested for two conditions:
a) Trial order / payment
b) Regular payment (none trial).

Because of varying trial fees, free trials, currency conversions, I can't compare it like this:

```
$has_trial_signup = WC_Subscriptions_Order::get_sign_up_fee( $order, $product->get_id() ) >= 0
```

It fails, when customer has just paid full, because it returns 0, hence $has_trial_signup is true, which is actually not the case.

In my case, signup fee can be $0, and still be a trial.
And signup fee can be $0, but not a trial.

So is this possible to just detect if order was trial order or full payment for Subscription orders, specifically "Parent Order".

**Comment by james-allan** [comment]
No there isn't. The closest thing I can think of is the line item meta `_has_trial`. That's only stored on subscription line items though not parent orders line items.

So you would need to do some mapping of parent order items to subscription items to determine if the parent order contains all free trial products.
