### ISSUE TITLE
Investigate whether we still need to show a downgrade notice for every major version

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#12]
Related WC Subscriptions issue: https://github.com/woocommerce/woocommerce-subscriptions/issues/4271

---

In WCS Core, we display a warning to store managers when they downgrade their Subscriptions version to a previous major version: i.e. 
4.0.0 -> 3.1.6

As mentioned on https://github.com/Automattic/woocommerce-subscriptions-core/issues/7#issuecomment-943799044, this notice is somewhat not relevant these days and was originally added to Subscriptions to notify store managers that have downgraded from 2.0 back to 1.5.

This is because in 2.0, Subscriptions changed significantly from being array stored on an order, to a custom order type, so downgrading back to 1.5 was really bad.

These days downgrading from Subscriptions 4.0 to 3.0 isn't a big deal at all so this issue is to look at updating when we show this notice:

Some options:
 - downgraded 2 major version
 - downgraded back to 1.5.x

**Comment by haszari** [comment]
@mattallan To me this feels like it's primarily focused on WooCommerce Subscriptions product, since the message only applies to the extension. Although I acknowledge the relevant code is in this repo, and may have implications for WCPay that we need to consider. Since this primarily impacts WC Subscriptions, would you mind moving the issue to that repo? 

I'm thinking we should consider this as part of 4.0 and it wasn't on my radar 😀

**Comment by mattallan** [comment]
@shendy-a8c I'm thinking we should get this change into WCS Core before releasing Subscriptions 4.0 to avoid stores seeing a "you downgraded" notice.

It's not urgent because the notice will only be shown to stores that have upgraded to 4.0 of the Subscriptions extension and then deactivate the Subscriptions extension and use WCPay Subscriptions feature, but it would be nice to not show this message.

Given it only affects a small user base what are your thoughts on getting this in Subscriptions 4.0?

From the description, I would go with the approach of only showing this notice to stores that have `downgraded back to 1.5.x` so the changeset should be pretty small :)
