### ISSUE TITLE
Undefined variable: $user_can_suspend in WCS_Customer_Suspension_Manager

### ISSUE THREAD

**Issue by vHeemstra** [Automattic/woocommerce-subscriptions-core#123]
## Note
Since there is no public place for the WooCommerce Subscriptions plugin code to report bugs, I'll submit it here. Since this package is part of the plugin.

## Describe the bug
When a user suspends their subscription the number of times he/she is allowed (if set value is not `unlimited`), PHP throws a warning:
`Notice: Undefined variable: user_can_suspend in /var/www/vhosts/domain-name.com/wp-content/plugins/woocommerce-subscriptions/includes/class-wcs-customer-suspension-manager.php on line 79`

The problem is inside `WCS_Customer_Suspension_Manager::can_customer_put_subscription_on_hold()`:
It's because `$user_can_suspend` is not set outside the `if` statement.

## Possible cause
Before the `if` statement, the method uses the variable name `$can_user_suspend`, which is similar, but not the same.

## Solution
Simply typo fix, I think. ;)

## To Reproduce
1. Looking at the source code of this function alone is enough. It's faulty code :)

### Expected behavior
No errors

### Actual behavior
Errors

## Product impact

- [X] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? unknown, probably

## Additional context
WooCommerce Subscriptions
Plugin version 4.0.2

**Comment by lkraav** [comment]
Yep this is real and should be caught by static analysis :thinking: 

Sample traceback https://sentry.io/share/issue/3ef5d8f8d4974545adf2c9c3794dc11b/

**Comment by mattallan** [comment]
Thanks for the report!
I've pushed up a PR to fix this in the main plugin repo and it should go out in 4.1 (due to go out today or sometime this week)
