### ISSUE TITLE
Active Subscriptions not updated when changing default payment method

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#128]
## Describe the bug

Updating the default payment method and choosing `Yes` to update active subscriptions to the new payment method does not update the subscription payment method as expected.

## To Reproduce

1. Create a new subscription order.
2. As a customer, add a new payment method.
3. Make the new payment method the default.
4. When prompted, select `Yes` to update subscriptions to the new payment method.
5. See payment method for the subscription is not updated.

## Product impact

- [x] Does this issue affect WooCommerce Payments? Yes https://github.com/Automattic/woocommerce-payments/issues/3729 
- [x] Does this issue affect WooCommerce Subscriptions? No

## Screenshots
Clicking `Make Default` on the Amex card ending in 0005. Presents the prompt.
![Screen Shot 2022-03-23 at 12 59 15 PM](https://user-images.githubusercontent.com/57298/159597470-55b65ab8-1eeb-4254-b253-049000b26218.png)
Clicking `Yes` does not update the payment method for the subscription
![Screen Shot 2022-03-23 at 12 59 35 PM](https://user-images.githubusercontent.com/57298/159597584-3cb09261-115b-42f3-8d56-0b451c4f4838.png)

**Comment by jrick1229** [comment]
We believe this is related to: 5187318-zen

**Comment by shendy-a8c** [comment]
To whoever work on this issue, please also make sure if this flow is covered in the e2e tests, maybe:
- https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-change-payment-method.spec.js, or
- https://github.com/Automattic/woocommerce-payments/blob/develop/tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.js

If so, were the e2e tests successful? If not, maybe it's good to cover this flow.

**Comment by shendy-a8c** [comment]
I also think that flow is already part of WCPay's critical flow:
- https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#change-payment-method-to-new-card
- https://github.com/Automattic/woocommerce-payments/wiki/Testing-instructions-for-critical-flows#change-payment-method-to-saved-card

**Comment by mouligreenlaw** [comment]
Merchant on 5187318-zen came back with another example of this issue.
They are currently manually renewing such subscriptions which fixes the issue but this is clearly not ideal in the long term.

**Comment by shendy-a8c** [comment]
Reopened because the [fix for HPOS](https://github.com/Automattic/woocommerce-subscriptions-core/pull/349) is not yet merged.
