### ISSUE TITLE
Update wcs_create_subscription to use CRUD compatible functions

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#129]
## Description

[Custom order tables](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/) are coming to WooCommerce. 

woocommerce-subscriptions-core needs to be updated from old methods of saving metadata  eg `update_post_meta()` to newer [CRUD](https://developer.woocommerce.com/2016/10/27/the-new-crud-classes-in-woocommerce-2-7/) capable functions as the old methods will not be supported with custom order tables.

This issue deals specifically with the `wcs_create_subscription()`

## Testing instructions

As this is a fundamental part of the subscriptions codebase, unit tests and thorough smoke testing should be done to confirm there are no regressions.

## Product impact

No issues have been created for WooCommerce Payments or WooCommerce Subscriptions as it is a library only update and won't affect end-users.

## Dev notes

Previous work was done in 3860-gh-woocommerce/woocommerce-subscriptions and was closed due to it becoming stale. So might be able to be used as a starting point.

## Additional context

pdjTHR-H1-p2

**Comment by mattallan** [comment]
This issue has been implemented in https://github.com/Automattic/woocommerce-subscriptions-core/pull/226
Closing. Thanks @brucealdridge
