### ISSUE TITLE
Reference to deprecated 'add_to_cart_ajax_redirect' function causes php fatal error

### ISSUE THREAD

**Issue by albertolevyespinosa** [Automattic/woocommerce-subscriptions-core#130]
## Describe the bug

When a simple product is added to cart with an existing subscription product and subscription rules avoid to have both types, Add to cart Ajax call gets a 500 response. Looking at php logs, the error is caused by trying to use non-existing function *redirect_ajax_add_to_cart* in *WC_Subscriptions_Cart_Validator* class:

    [30-Mar-2022 15:49:36 UTC] PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class WC_Subscriptions_Cart_Validator does not have a method "redirect_ajax_add_to_cart" in C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php:307
    Stack trace:
    #0 C:\xampp\htdocs\testsubscriptions\wp-includes\plugin.php(189): WP_Hook->apply_filters(Array, Array)
    #1 C:\xampp\htdocs\testsubscriptions\wp-content\plugins\woocommerce\includes\class-wc-ajax.php(191): apply_filters('woocommerce_add...', Array)
    #2 C:\xampp\htdocs\testsubscriptions\wp-content\plugins\woocommerce\includes\class-wc-ajax.php(425): WC_AJAX::get_refreshed_fragments()
    #3 C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php(307): WC_AJAX::add_to_cart('')
    #4 C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
    #5 C:\xampp\htdocs\testsubscriptions\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
    #6 C:\xampp\htdocs\testsubscriptions\wp-content\plugins\woocommerce\includes\class-wc-ajax.php(90): do_action('wc_ajax_add_to_...')
    #7 C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php(307): WC_AJAX::do_wc_ajax('')
    #8 C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php(331): WP_Hook->apply_filters(false, Array)
    #9 C:\xampp\htdocs\testsubscriptions\wp-includes\plugin.php(474): WP_Hook->do_action(Array)
    #10 C:\xampp\htdocs\testsubscriptions\wp-includes\template-loader.php(13): do_action('template_redire...')
    #11 C:\xampp\htdocs\testsubscriptions\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...')
    #12 C:\xampp\htdocs\testsubscriptions\index.php(17): require('C:\\xampp\\htdocs...')
    #13 {main}
      thrown in C:\xampp\htdocs\testsubscriptions\wp-includes\class-wp-hook.php on line 307

## To Reproduce

1. Configure Woocommerce Subscriptions without mixed payment (cannot buy subscription product with other products at a time): ![captura3](https://user-images.githubusercontent.com/72998568/160880547-4f5045bb-97ca-4103-9d72-a0ec815c2f69.png)
2. Configure a subscription variable product and avoid having more than one active subscription: ![captura4](https://user-images.githubusercontent.com/72998568/160881061-ff443484-ebe1-44e4-ae2a-71f34b87644e.png)
3. As guest, add the product in step 2 to cart: ![captura1](https://user-images.githubusercontent.com/72998568/160878443-c3d273f7-0f91-4d5a-a359-85435eb76dd8.png)
4. Then, try to add a simple product to cart: ![captura2](https://user-images.githubusercontent.com/72998568/160881716-26bd2c1d-bfff-4d3d-9efc-8b738a3b9d30.png)

### Expected behavior

Simple product is added to cart while suscription product is removed and a notice reminds both products cannot be bought at the same time.

### Actual behavior

- Add to cart button remains spinning forever.
- Ajax call gets a 500 error.
- Php log shows a fatal error.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? Yes
- [ ] Does this issue affect WooCommerce Payments? Tbc

## Additional context

- Wordpress version: 5.9.2
- Woocommerce version: 6.3.1
- Woocommerce Subscriptions version: 4.1.0

## Possible diagnostic and solution
Following the log, I found *WC_Subscriptions_Deprecation_Handler* class with a list of deprecated functions and their substitutions. There, I found *redirect_ajax_add_to_cart* function is now called *add_to_cart_ajax_redirect*.

Not sure if this handler should be managing calls to deprecated functions, but I made the substitution in *maybe_empty_cart* function of *WC_Subscriptions_Cart_Validator* class to now use *add_to_cart_ajax_redirect* and now it's working as expected.

**Comment by haszari** [comment]
Marking as low priority as the combination of settings means this won't be affecting the majority of merchants. 

However, since this is a 500 error with standard settings and no customisation, it would be great to tidy this up.

**Comment by haszari** [comment]
Thanks for the report @albertolevyespinosa  ! Feel free to open a PR if you have a suggested fix.
