### ISSUE TITLE
Replace code which uses `get_posts()` to get Orders post types with `wc_get_orders()`

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#144]
## Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), we need to begin to think about updating the Subscriptions Core library to remove any code that is calling WP Post API functions.

In this issue we're tackling uses of `get_posts()` where `shop_order` post type is passed. Subscriptions and products are fine as they're staying in the wp posts table.

## How to update code?

We should be able to replace most cases of `get_posts` with `wc_get_orders()`. To search for custom parameters we can use the approach outlined here: https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support

## Changes needed

- [x] [`get_users_subscription_orders`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/97c279bdb6131462de9e90161a6a172ce0447293/includes/class-wc-subscriptions-order.php#L617)
  - This function is not being used by any of our code including in WC Payments and WC Subscriptions so updating this is very low priority/impact
 - [x] [`wcs_get_subscription_orders`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/wcs-order-functions.php#L425)

## Code to ignore

- `class WCS_Related_Order_Store_CPT` - will be handled separately in #145 
- [`WCS_PayPal_Standard_IPN_Handler::get_order_id_and_key()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/gateways/paypal/includes/class-wcs-paypal-standard-ipn-handler.php#L604)
  - This can probably be ignored for now because `'shop_order'` post type is never queried (even though it's the default option when calling the function). I believe this default option was pre-WC subscriptions 2.0 before a subscription post type existed and we had to use the parent order ID.
- `class WCS_Repair_2_0` - We're going to disable old repair scripts when HPOS is enabled
- `class WCS_Upgrade_2_0` - We're going to disable old upgrade scripts when HPOS is enabled

## Product impact

- Does this feature affect WooCommerce Subscriptions? yes
- Does this feature affect WooCommerce Payments? yes

**Comment by shendy-a8c** [comment]
Reopen since https://github.com/Automattic/woocommerce-subscriptions-core/pull/161 doesn't address all the expectations from this issue.
