### ISSUE TITLE
Upgrading/refactoring the `WCS_Related_Order_Store_CPT` class for custom order tables

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#145]
This approach was originally discussed internally on this p2: pdjTHR-Y8-p2

## Description

The `WCS_Related_Order_Store_CPT` class by name is associated heavily with Orders being a custom post type. With WC Orders moving to custom order tables we need to rethink how this class is named and how it interacts with orders to remove any assumptions that orders are stored in the posts table.

#### What changes are needed?

- [x] Update `WCS_Related_Order_Store_X` classes (including cache) to replace WP Post APIs with modern APIs i.e. replace the `get_posts()` with `wc_get_orders()`
- [x] Integrate with the `WC_Order_Query` to enable us to query by order-relationship types. There's a guide on how to do that [here](https://href.li/?https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query#adding-custom-parameter-support).
- [ ] Rename the class to remove the CPT suffix
   - Because the `WCS_Related_Order_Store_CPT` class would no longer be directly using post APIs we should remove/replace the CPT suffix unshackling us to that data structure. This would likely mean deprecating a copy of the old class or some other way to do this in a backward-compatible way.

## Product impact

- Does this feature affect WooCommerce Subscriptions? yes
- Does this feature affect WooCommerce Payments? yes

## Dev notes

The approach mentioned in this issue is not final. Before working on this issue, check back on the internal p2 (pdjTHR-Y8-p2) to see if there have been any changes to the final approach

**Comment by AashikP** [comment]
A related report in 5676548-zen

Internal discussion: p1667405287233049-slack-C02BW3Z8SHK
