### ISSUE TITLE
Refactor the Subscriptions Tracker class to replace direct DB queries to fetch WC Order data from wp posts/postmeta tables

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#147]
## Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), we need to begin to think about updating the Subscriptions Core library to remove any code that makes direct DB queries to the post table when fetching Order related data.

In this issue, we're tackling the only uses of `$wpdb->get_col()` where the 'shop_order' post type is being queried.

## Code that needs updating
 - [x] [`WC_Subscriptions_Tracker::get_subscription_orders()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wc-subscriptions-tracker.php#L127-L167)

## How to update code
Direct DB queries should be replaced with wc_get_orders()/WC_Order_Query, however I'm not exactly sure if every use case is as simple as that. If there's some complicated code/queries we may have to look at refactoring some code as part of tackling this issue.

## Product impact

- Does this feature affect WooCommerce Subscriptions? yes
- Does this feature affect WooCommerce Payments? yes

## Dev notes

I've marked this as critical because if not implemented, we'll get incorrect/empty values sent to tracker for the number of switch, renewal and resubscribe orders on the store.

To call [`WC_Subscriptions_Tracker::add_subscriptions_tracking_data()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/9cc2b85f30c7ae18020fcff52a953fde4ca8b7a0/includes/class-wc-subscriptions-tracker.php#L32), run [`WC_Tracker::get_tracking_data()`](https://github.com/woocommerce/woocommerce/blob/2de5a8f08657a70987f48421dc43706890b96e4d/plugins/woocommerce/includes/class-wc-tracker.php#L117) with the WP Console plugin.  

## Additional context

Project thread: pdjTHR-Xp-p2

**Comment by Jinksi** [comment]
After familiarising myself with what this tracking data is and where it is used, I added the following note to the issue description:

To call [`WC_Subscriptions_Tracker::add_subscriptions_tracking_data()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/9cc2b85f30c7ae18020fcff52a953fde4ca8b7a0/includes/class-wc-subscriptions-tracker.php#L32), run [`WC_Tracker::get_tracking_data()`](https://github.com/woocommerce/woocommerce/blob/2de5a8f08657a70987f48421dc43706890b96e4d/plugins/woocommerce/includes/class-wc-tracker.php#L117) with the WP Console plugin.

**Comment by Jinksi** [comment]
I've added the `blocked` label due to the requirement of the `get_subscriptions_count_by_status` function from #372.
