### ISSUE TITLE
Remove old upgrade/repair scripts from the Subscription Core codebase

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#150]
## Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), some of our old subscription/order repair and upgrade scripts that use direct database queries on orders will no longer work.

Rather than refactoring/updating these functions, we discussed (pdjTHR-H1-p2#comment-859) the idea of removing these older functions and then have a clear documented path for stores to upgrade from very old versions of Subscriptions.

## Proposed changes

In the link shared above, we decided to remove any upgrade/repair scripts from before 3.0 (last major version) so the changes to close this issue would be:
 - [ ] Deprecate any upgrade/repair scripts classes from before 3.0.
 - [ ] Make sure no deprecated upgrade/repair classes are ran (update the `WC_Subscriptions_Upgrader` class to not trigger an old upgrades)
 - [ ] Update the `WC_Subscriptions_Upgrader` class to display an admin notice or some sort of error admin page when a store is upgrading from an unsupported version with a link to documentation with Steps on how to upgrade.

## Product impact

- Does this feature affect WooCommerce Subscriptions? yes
- Does this feature affect WooCommerce Payments? yes
  - While unlikely, there's potential for these changes to impact WC Pay in that a store could have been using an old version of subscriptions and then switched to the latest version bundled in WC Payments. 

## Dev notes

Something worth mentioning is that none of the repair scripts have code that will break when orders are moved to custom tables, so we could technically keep them. My thinking is that we just remove them because it would seem odd if the upgrade script has been removed for a particular version, but the repair script still runs.

## Additional context

Project thread: pdjTHR-Xp-p2
Discussion on removing scripts before 3.0: pdjTHR-H1-p2

**Comment by brucealdridge** [comment]
This work may be dependent on (or be able to close off) #155

**Comment by haszari** [comment]
@mattallan  / @brucealdridge will this be handled as part of HPOS project? I'm assuming yes, so tagged `projects` and removed from maintenance board.
