### ISSUE TITLE
Replace code which uses `get_post_type( $order_id )` with wc data store equivalent

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#153]
## Description

With Custom Order Tables being worked on by the WC Core team ([public announcement](https://developer.woocommerce.com/2022/01/17/the-plan-for-the-woocommerce-custom-order-table/)), we need to begin to think about updating the Subscriptions Core library to remove any code that is calling WP Post API functions.

In this issue, we're tackling only the uses of `get_post_type( $post_id )` where an order ID is passed.

## How to update code?

Existing code using `get_post_type( $order_id )` needs to be replaced with `WC_Data_Store::load( 'order' )->get_order_type( $order_id )`. For example:

```
if ( 'shop_order' !== get_post_type( $args['order_id'] ) ) {
    return;
}
```

Would look like this:

```
if ( 'shop_order' !== WC_Data_Store::load( 'order' )->get_order_type( $order_id ) ) {
    return;
}
```

## Changes needed
- [x] [`wcs_get_subscriptions()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/039f0a395c839fbc40c1291d32d554db06723b3f/wcs-functions.php#L443)
- [x] [`WC_Subscriptions_Manager::maybe_trash_subscription()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wc-subscriptions-manager.php#L796)
- [x] [`WC_Subscriptions_Manager::maybe_untrash_subscription()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wc-subscriptions-manager.php#L813)
- [x] [`WC_Subscriptions_Manager::maybe_delete_subscription()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wc-subscriptions-manager.php#L828)
- [x] [`WCS_Cart_Renewal::cart_items_loaded_from_session()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/c87beae8bb1996e67f6c8ed16d212048c4df6155/includes/class-wcs-cart-renewal.php#L394)
- [x] [`wcs_get_edit_post_link()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/wcs-helper-functions.php#L65)
- [x] [`WCS_Admin_Meta_Boxes::add_meta_boxes()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/ad42d34fc632327333486d09577740a38f9f76f8/includes/admin/class-wcs-admin-meta-boxes.php#L88)

## Code to ignore
 - [`WC_Subscriptions_Synchroniser::get_sign_up_fee()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wc-subscriptions-synchroniser.php#L1531)
   - Deprecated in 2.x and will be removed
 - [`WCS_Cached_Data_Manager::purge_delete()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/2a0654bf0385cc3e5b097943aea5589e843b05d0/includes/class-wcs-cached-data-manager.php#L73)
   - Deprecated in 2.3
## Product impact

- Does this feature affect WooCommerce Subscriptions? yes
- Does this feature affect WooCommerce Payments? yes

## Additional context

Product thread: pdjTHR-Xp-p2

**Comment by shendy-a8c** [comment]
@mattallan I'm wondering why [the use of `get_post_type()` in `wcs_is_subscription()`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/d917274155b2870da5c3b6dbe6d8c36f0572856d/wcs-functions.php#L42) isn't covered in this issue and if it's going to be covered in other issue.

**Comment by mattallan** [comment]
Hey @shendy-a8c thanks for asking! I didn’t update that usage of get_post_type get WC Subscription’s are still staying in the posts table so we can still use this function.

Feel free to update this line if you want to though :)
