### ISSUE TITLE
Intermittent error with unit tests

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#157]
## Describe the bug
The recent updated to the CI using github actions has surfaced an intermittent issue with the test suite.

in `WC_Subscriptions_Test::test_update_status_to_pending_canellation` we validate that a timestamp is saved in the database. Due to phpunit deprecating and removing the `$delta` parameter on the `assertEquals` function. This code now fails intermittently.

```
There was 1 failure:

1) WC_Subscriptions_Test::test_update_status_to_pending_canellation
Failed asserting that 1649912371 matches expected 1649912372.

/home/runner/work/woocommerce-subscriptions-core/woocommerce-subscriptions-core/tests/unit/test-class-wc-subscriptions.php:1149
```

[View the full logs](https://github.com/Automattic/woocommerce-subscriptions-core/runs/6018810069?check_suite_focus=true)

https://github.com/Automattic/woocommerce-subscriptions-core/blob/8eea2a9bd5e6cafda6655bcda3fb754e2ea7936a/tests/unit/test-class-wc-subscriptions.php#L1146

This will need to be updated to `assertEqualsWithDelta` it must have been missed in 8eea2a9bd5e6cafda6655bcda3fb754e2ea7936a

**Comment by mattallan** [comment]
Closed with [a218e45](https://github.com/Automattic/woocommerce-subscriptions-core/pull/159/commits/a218e4549b1017bce6c82aecfccdc78d03ace860) in #159
