### ISSUE TITLE
Allow database upgrades on headless sites.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#158]
## Description

There is no way to upgrade the database (when required) on headless sites. For previously required upgrades, they required either manually clicking a button or by a user visiting `wp-admin`. 

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions? yes
- [x] Does this feature affect WooCommerce Payments? yes

## Additional context

Issue stemming from the bug found in #155 
p81Rsd-J3-p2#comment-1025

**Comment by haszari** [comment]
As I understand it this is an unusual use case – a site where wp-admin is rarely visited! That said, we want to ensure our upgrade processes are robust and work well for a variety of use cases 🚀 

@brucealdridge  (or anyone else!) – would be good to flesh out this issue with more context to help us prioritise. 

- How to reproduce on a new / clean site.
- The impact of the bug – i.e. specifically what breaks. 
- Specific relevant details of how this impacted sites we know of – i.e. real use case for "headless".
- Workarounds for the issue - e.g. visit or automatically request an admin page after plugin update.
- Options or ideas for how to fix this - e.g. add a wp-cli command to manually run database upgrades, or make the upgrade processing more robust so it doesn't require wp-admin load.

**Comment by haszari** [comment]
Closing and adding relevant info to earlier reported #155
