### ISSUE TITLE
Division by Zero fatal error in renewal logic (PHP8)

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#175]
## Describe the bug

In php8 a Division By Zero [now throws an error](https://3v4l.org/8rait) whereas in older versions of php it only triggered a warning.
While there is no clear way to reproduce this error there have been instances of customers being affected.

A customer has flagged the following specific line during renewals 
https://github.com/Automattic/woocommerce-subscriptions-core/blob/97b448a082c61d684bbd29a2033788ffb6bced4d/includes/class-wcs-cart-renewal.php#L454

Wrapping this line in a try/catch, catching `DivisionByZeroError` seems to be the best solution as this will not change the behavior on older versions of php.

## How to reproduce
(Steps pasted from other issue)

It is tough to reproduce this issue as it is intermittent. In one of the older versions of WooCommerce Subscriptions I was able to reproduce this issue by:

1. Create two active subscription orders
1. Create pending renewal orders for both of them.
1. Open the customer payment page side by side in the browser for both renewals.
1. Close the one you opened last, and proceed to pay for the earlier one.
1. You'll see the DivisionByZeroError in logs. (This may be due to cart hashes clashing.)

But now with the latest version of WooCommerce Subscriptions, I am not able to reproduce the error using the steps above.

Next, I came across this ticket 5228964-zen, where the user is still facing the same error using the latest version of WooCommerce Subscriptions.

I decided to do some tests on my site (using Subs 4.2.0). For an active subscription order,

1. I created a pending renewal order.
1. Then, I deleted the item in the on-hold subscription order.
1. I tried making a payment for the pending renewal order using the "Customer payment page" link.
1. I was able to get the DivisionByZeroError in logs after the payment.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? Yes, 4359-gh-woocommerce/woocommerce-subscriptions
- [x] Does this issue affect WooCommerce Payments? **Assuming yes – unconfirmed**

## Additional context

5228964-zen

**Comment by melek** [comment]
A customer in 5241049-zen got this error when a customer renewed their subscription (PHP Version 8.0.16):

```
2022-05-24T15:26:33+00:00 CRITICAL Uncaught DivisionByZeroError: Division by zero in /public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wcs-cart-renewal.php:454 
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(307): WCS_Cart_Renewal->get_cart_item_from_session()
#1 /public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2 /public_html/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(163): apply_filters()
#3 /public_html/wp-includes/class-wp-hook.php(307): WC_Cart_Session->get_cart_from_session()
#4 /public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#5 /public_html/wp-includes/plugin.php(474): WP_Hook->do_action()
#6 /public_html/wp-settings.php(609): do_action()
#7 /public_html/wp-config.php(87): require_once('/public_html/wp...')
#8 /public_html/wp-load.php(50): require_once('/public_html/wp...')
#9 /public_html/wp-admin/admin-ajax.php(22): require_once('/public_html/wp...')
#10 {main}
thrown in /public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wcs-cart-renewal.php on line 454
```

They report that the subscription had the following note: `Payment method changed from “Credit or Debit Card” to “Credit or Debit Card” by the subscriber. (24th May 2022 at 4:26 pm)`. They also included the coinciding Stripe logs from the same time during a manual renewal; those full logs are viewable in 35349195-hc.

Hope this helps!

**Comment by haszari** [comment]
Thanks for logging this in core @brucealdridge 🙌 

Labeling this as high priority and adding to current column on maintenance board, [since this is a fatal error on some environments (PHP8)](https://github.com/woocommerce/woocommerce-subscriptions/issues/4359#issuecomment-1135271073). 

Although we don't have a reliable way to reproduce this error, we should protect against the divide by zero error and fail gracefully.

It's highly likely this affects WCPay in the same way, so we'll need to keep that in mind when implementing a fix.

**Comment by Brianmitchtay** [comment]
19789575-hc Seeing this error again. This user is only seeing the error when a specific user logs into the site. 

```
[06-Jun-2022 21:28:00 UTC] PHP Fatal error:  Uncaught DivisionByZeroError: Division by zero in /home/ypacarts/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/class-wcs-cart-renewal.php:454
```



Until we have a fix in place, is advising the users to revert to a pre 8.0 version of PHP our best path for circumventing this? That's what I've done in this case.
