### ISSUE TITLE
Subscription ID title not displayed in `My account > Subscriptions` in block-based / full site editing (FSE) themes (e.g. Twenty Twenty Two)

### ISSUE THREAD

**Issue by haszari** [Automattic/woocommerce-subscriptions-core#181]
## Describe the bug
Subscriptions are shown in customer `My account` area, allowing subscriber to change payment details and view info (etc). 

The subscription id is shown as a prominent heading, but this is not visible in Twenty Twenty Two. 

## To Reproduce
0. Activate Twenty Twenty Two (latest default WP theme).
1. Ensure you have subscriptions functionality (WCPay or WC Subscriptions active), a subscription product published.
2. As a shopper, purchase subscription. 
3. Go to `My account` and click on `Subscription[s]`. Click one of the subscriptions to view details.
4. No subscription ID heading!

### Expected behavior
See subscription id / title in Storefront or Twenty Twenty One:

<img width="1330" alt="Screen Shot 2022-06-09 at 8 18 08 AM" src="https://user-images.githubusercontent.com/4167300/172710125-f734354d-fd4a-4e86-b787-6e4203ee57a1.png">

<img width="1066" alt="Screen Shot 2022-06-09 at 8 17 57 AM" src="https://user-images.githubusercontent.com/4167300/172710144-385834a8-d65a-40ff-8498-b6f5f40db5d2.png">

### Actual behavior

<img width="1151" alt="Screen Shot 2022-06-09 at 8 17 24 AM" src="https://user-images.githubusercontent.com/4167300/172710158-bf018124-3eda-4041-8f74-60377ed7cb09.png">

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? **_yes_** 4371-gh-woocommerce/woocommerce-subscriptions
- [ ] Does this issue affect WooCommerce Payments? **_yes_** https://github.com/Automattic/woocommerce-payments/issues/4315

**Comment by brucealdridge** [comment]
Have spent some time looking into it.
The title is set correctly in [change_my_account_endpoint_title()](https://github.com/Automattic/woocommerce-subscriptions-core/blob/bea26b22853c0a0442af9c5357791dfc49d136a2/includes/class-wcs-query.php#L94-L115) which is called via the `woocommerce_endpoint_view-subscription_title` hook.

Based on logs, it looks like the `My account` title is getting set before this hook is being called. So there maybe some challenges in resolving this.

I managed to pull some logs, with the relevant hooks being called
```
03:15:25.915 the_title 
    $arg = 'My account' 
    wp-includes/post-template.php:171
03:15:25.915 render_block_core/post-title 
    <h1 style="margin-bottom: var(--wp--custom--spacing--medium, 6rem);" class="alignwide wp-block-post-title">My account</h1> 
    wp-includes/class-wp-block.php:299
03:15:25.915 the_title 
    $arg = 'My account' 
    wp-includes/post-template.php:171
03:15:25.916 the_title 
    $arg = 'My account' 
    wp-includes/post-template.php:171
03:15:25.916 woocommerce_endpoint_view-subscription_title 
    return 'Subscription #%s'
    wp-content/plugins/woocommerce/includes/class-wc-query.php:178
03:15:26.024 single_post_title $arg = 'My account' 
    wp-includes/general-template.php:1480
```

**Comment by haszari** [comment]
> Based on logs, it looks like the My account title is getting set before this hook is being called. So there maybe some challenges in resolving this.

@brucealdridge - Any idea why this is different for Twenty Twenty Two? 

Do you think this is an issue with the theme, i.e. we should report upstream?

**Comment by haszari** [comment]
@brucealdridge Could also reach out to blocks / store editing teams to see if they have any suggestions.

**Comment by brucealdridge** [comment]
> @brucealdridge - Any idea why this is different for Twenty Twenty Two?
> 
> Do you think this is an issue with the theme, i.e. we should report upstream?

It seems to be as Twenty Twenty Two is a Full Site Editing theme. Blockbase has the same problem.

**Comment by haszari** [comment]
This issue is unrelated to subscriptions, all the `My account` subsection titles are broken in Twenty Twenty-Two.

I've reported this to WC core and will close this issue.

- https://github.com/woocommerce/woocommerce/issues/33774
