### ISSUE TITLE
Related Orders table not displayed when viewing new Edit Order page (COT enabled stores)

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#192]
## Describe the bug

When COT is enabled, the related-order table is not shown when viewing the Edit Order page for subscription orders.

![image](https://user-images.githubusercontent.com/2275145/183004706-f9e0a4a1-08e0-4578-a367-7f8ecb2fae9b.png)

I haven't done much digging into this but something I noticed is when COT is enabled, the view order URL changes from the edit post url to a new admin url:

Old : `/wp-admin/post.php?post=1360&action=edit`
New: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`

I've opened an issue to address the URL issue: https://github.com/Automattic/woocommerce-subscriptions-core/issues/193

## To Reproduce

1. Enable the COT feature and turn on COT ([see guide here](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#easy-way))
2. Go into **WooCommerce > Settings > Advanced > Custom Data Stores**
3. Make sure "Use the WooCommerce orders tables" is enabled
4. Purchase a subscription and note the order ID
5. From WP admin dashboard, go to **WooCommerce > Orders** and view the new order
6. Notice there's no related orders table

### Expected behavior

Parent orders and renewal orders have a related orders table with details about all subscription related order.

<img width="796" alt="image" src="https://user-images.githubusercontent.com/3147296/200215506-43f00ebc-f4b8-4602-9c60-d5d137a1178a.png">

### Actual behavior

Related orders table isn't loaded.
When Custom order tables

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by mattallan** [comment]
More details and code examples on how to update metaboxes to support both post orders and cot orders can be found here: https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions

**Comment by Jinksi** [comment]
An example of the related orders table that should be visible:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/3147296/200215506-43f00ebc-f4b8-4602-9c60-d5d137a1178a.png">

**Comment by Jinksi** [comment]
> More details and code examples on how to update metaboxes to support both post orders and cot orders can be found here: [Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions)

@mattallan This link has changed to https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#audit-for-order-administration-screen-functions

**Comment by mattallan** [comment]
Thanks @Jinksi I've updated it!
