### ISSUE TITLE
Orders in the related orders table should link to the new Edit Order URL when HPOS is enabled

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#193]
## Describe the bug

When COT is enabled on a store the proper Order admin url is now: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`
When viewing the related orders table on a subscription, the links still send you to the old URL: `/wp-admin/admin.php?page=wc-orders&id=123&action=edit`

From my testing, this URL still appears to work and performing actions (like updating the order status) while on the WP POST Edit Order URL everything seems to work as normal. I think this is because when orders are migrated to the new custom order table, a post with `shop_order_placeholder` post type remains in the post table to link the post.id to the cot.id and keep any actions to the post.id in sync with the order data now in COT.

From this slack thread (p1658827038810479-slack-C9QDV4TL4), we cannot rely on `shop_order_placeholder` being around forever, so we'll need to update this:

> we are not relying on placeholders to be present in anything except for our mitigation of cot.id === post.id . so someone can disable them. but it's not an option in ui at this point
>
> so while we will allow disabling placeholders in the distant future, those users would be part of our experienced user cohort, and we can address that compatibility later.

## To Reproduce

1. Enable the COT feature and turn on COT ([see guide here](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#easy-way))
1. Go into WooCommerce > Settings > Advanced > Custom Data Stores
1. Make sure "Use the WooCommerce orders tables" is enabled
1. Purchase a subscription
1. From WP admin dashboard, go to WooCommerce > Subscriptions and view the new subscription
1. Click on the link to the parent order in the related orders table and notice the URL is different to the URL you would be redirected to if you went to **WP Admin > WooCommerce > Orders** and viewed an order

### Expected behavior

Related orders table links to the correct orders URL when COT is enabled.

### Actual behavior

Related orders table links to the edit post URL when COT is enabled which is relying on `shop_order_placeholder` posts existing on stores to link post IDs to COT IDs.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by haszari** [comment]
@Jinksi I'm removing blocked label based on the PR - if this is still blocked please clarify :)
