### ISSUE TITLE
Spike: Avoid `_post` hooks in `WCS_Post_Meta_Cache_Manager` (e.g. `update_post_meta`, `trashed_post`)

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#194]
> **Note** - As part of tackling this issue, we will need to investigate what's broken and possible solutions.

## Describe the bug

From the COT upgrade guide, there's a section on [auditing our code](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#auditing-the-code-base-for-direct-db-access-usage):

> To support custom order tables, a good place to start is to audit your code base for direct DB access and usage of WordPress APIs that we won't be using any more. You can search using following regexes to perform this audit

Using their regex string, one area of code that was highlighted was our `WCS_Post_Meta_Cache_Manager` class.
This class's [init function](https://github.com/Automattic/woocommerce-subscriptions-core/blob/9ce5295854ff935426b13e8e216265f10f06ec41/includes/class-wcs-post-meta-cache-manager.php#L37) hooks onto various post updated/added/deleted and meta changed hooks to then make sure our related order cache is updated properly:

```
// When the post for a related order is deleted or untrashed, make sure the corresponding related order cache is updated
add_action( 'before_delete_post', array( $this, 'post_deleted' ) );
add_action( 'trashed_post', array( $this, 'post_deleted' ) );
add_action( 'untrashed_post', array( $this, 'post_untrashed' ) );

// When a related order post meta flag is modified, make sure the corresponding related order cache is updated
add_action( 'added_post_meta', array( $this, 'meta_added' ), 10, 4 );
add_action( 'update_post_meta', array( $this, 'meta_updated' ), 10, 4 );
add_action( 'deleted_post_meta', array( $this, 'meta_deleted' ), 10, 4 );

// Special handling for meta updates containing a previous order ID to make sure we also delete any previously linked relationship
add_action( 'update_post_metadata', array( $this, 'meta_updated_with_previous' ), 10, 5 );

// Special handling for meta deletion on all posts/orders, not a specific post/order ID
add_action( 'delete_post_metadata', array( $this, 'meta_deleted_all' ), 100, 5 );
I haven't witnessed any issues with testing our plugin yet but under the heading of "Auditing our code yet but 
```

I haven't tested broken flows with us using these old hooks with COT enabled on the store so part of tackling this issue is also investigating impact.

My understanding is that these hooks just won't fire anymore when a store is using Custom Order Tables meaning our related order cache won't update properly but we'll need to confirm.

**Comment by haszari** [comment]
I've renamed this to clarify. Looks like the first step here is to audit to confirm the usage of deprecated or not-recommended hooks, and the impacted flows, so I've made this issue a research spike. FYI @mattallan - feel free to edit to clarify.

**Comment by haszari** [comment]
Update: when we story pointed this, we assumed that this issue would cover auditing the deprecated hooks and fixing all impacted code (and flows). @mattallan can you update the issue to clarify the outcome?

If we do need a separate spike before implementing fixes (i.e. if the work required here needs investigation), let me know.
