### ISSUE TITLE
When COT is enabled, Subscriptions are not trashed when the parent order is deleted

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#195]
## Describe the bug

When you delete a parent order of a subscription, the subscription should also be trashed. This functionality is handled by our [`maybe_trash_subscription`](https://github.com/Automattic/woocommerce-subscriptions-core/blob/9ce5295854ff935426b13e8e216265f10f06ec41/includes/class-wc-subscriptions-manager.php#L796-L804) which is hooked onto the `wp_trash_post` hook.

When custom order tables is enabled, trashing the parent order does not trash the subscription.
I think the problem is caused by the `wp_trash_post` hook not being fired now that orders are not posts, but it may also be caused by `wcs_get_subscriptions_for_order()` not finding the subscriptions correctly (will need to confirm when implementing the fix)

There has been some internal discussion questions related to the use of these hooks in this slack thread: p1659617204621119-slackC9QDV4TL4

## To Reproduce

1. Enable COT on your store (see [guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Purchase a subscription
3. Make note of the parent order ID
4. Manually delete the order using code (i.e `$order = wc_get_order( 123 ); $order->delete( true );`)
   - Doing this manually is required because the "Move to Trash" button on the Edit Order page doesn't delete the COT order. It currently only deletes the order in post table
5. Confirm the parent order no longer exists in **WooCommerce > Orders** table
6. Subscription still is active though :x:

### Expected behavior

It's expected that when a parent order is deleted, the subscription is also deleted.

### Actual behavior

Subscription is not being deleted when deleting an order stored in COT.

**Comment by brucealdridge** [comment]
Somewhat duplicated by #221
