### ISSUE TITLE
With COT enabled, multiple PHP notices are displayed when updating/saving an order linked to a subscription

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#196]
## Describe the bug

With COT enabled, updating/saving an order via the Edit Order page results in the following PHP notices:

![image](https://user-images.githubusercontent.com/2275145/183571519-39cdd591-416c-4e48-be04-e5ccab30ab8f.png)

The backtrace points to the following functions which are accessing subscription/order properties which:
 - `WCS_Admin_Meta_Boxes->remove_meta_box_save`
 - `WCS_Meta_Box_Schedule::save`
 - `WCS_Meta_Box_Subscription_Data::save`

We should change these to just `$object->get_type()`.

## To Reproduce

1. Enable COT on your store (see [guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Purchase a subscription
3. Make note of the parent order ID
4. Got to **WooCommerce > Orders > Edit Order** for the order just purchased
5. Update the status of the order to on-hold and hit "Update"
6. Notice the errors at the top of the page

### Expected behavior

No errors are to be shown after updating an order.

### Fixed by

- [x] #280 
- [x] #281 
- [x] #282

**Comment by jbordonado** [comment]
FYI, GlobalStep also spotted this notice while testing a "Capture later" flow.
Once you hit update for a "Capture later" action on an order, it will succeed and show that notice.
For reference: p1660036342085529-slack-C011ENB20Q1
