### ISSUE TITLE
With COT enabled and no sync, related orders link on admin subscriptions list does not show the related orders.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-subscriptions-core#199]
## Describe the bug

With custom order table and without sync, on the admin subscriptions list page, the link to the related orders of certain subscription does not show the related orders.

![Screen Shot 2022-08-12 at 03 27 47](https://user-images.githubusercontent.com/73803630/184236799-98e8ec42-abf5-49db-b40c-b672b7f3d80d.png)

![Screen Shot 2022-08-12 at 03 28 57](https://user-images.githubusercontent.com/73803630/184236821-f3b3ad7f-5098-4924-b2ac-1eb612e61819.png)

## To Reproduce

1. Install WooCommerce with custom order table feature.
2. Enable custom order table.
3. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > select `Use the WooCommerce orders tables` and uncheck `Keep the posts table and the orders tables synchronized`.
4. Purchase a subscription.
5. Go to admin subscriptions list page (wp-admin > WooCommerce > Subscriptions).
6. Click on a link under the `Orders` column.

### Expected behavior

Related orders of the specified subscriptions should show.

### Actual behavior

Related orders of the specified subscriptions do not show.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes, 4390-gh-woocommerce/woocommerce-subscriptions.
- [x] Does this issue affect WooCommerce Payments? yes, https://github.com/Automattic/woocommerce-payments/issues/4570.

**Comment by Jinksi** [comment]
Does this rely on #223?
