### ISSUE TITLE
With COT no sync, sorting subscriptions by Next Payment and Last Order Date does not give the correct ordering.

### ISSUE THREAD

**Issue by shendy-a8c** [Automattic/woocommerce-subscriptions-core#200]
> **Warning**
> When HPOS is enabled, this screen will need to be replaced as standard WP screens can not be used with the new Order tables. The Subscriptions listings when HPOS is enabled will now need a controller similar to https://github.com/woocommerce/woocommerce/blob/8fbdbaf3540786deeb4fc7d6b8d57a6b4b5dea6c/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php
> see also #223

## Describe the bug

With custom order table enable but without sync enabled, sorting subscriptions on list admin page by `Next Payment` and `Last Order Date` does not give the correct ordering.

![Screen Shot 2022-08-12 at 05 13 06](https://user-images.githubusercontent.com/73803630/184251489-6734d14d-84ab-44a3-a49c-5a399f1380cd.png)

![Screen Shot 2022-08-12 at 05 12 53](https://user-images.githubusercontent.com/73803630/184251498-511bbdd1-07f1-46c2-9295-0a745f7fe73f.png)

![Screen Shot 2022-08-12 at 05 12 33](https://user-images.githubusercontent.com/73803630/184251502-86c83719-85f0-4621-97db-e22d65a0acdb.png)

## To Reproduce

1. Install WooCommerce with custom order table feature.
2. Enable custom order table.
3. Go to wp-admin > WooCommerce > Settings > Advanced > Custom data stores > select `Use the WooCommerce orders tables` and uncheck `Keep the posts table and the orders tables synchronized`.
4. Purchase several subscriptions.
5. Go to admin subscriptions list page (wp-admin > WooCommerce > Subscriptions).
6. Click on the column `Next Payment` and `Last Order Date` to order by them ascending and descending.

### Expected behavior

Subscriptions sorted by the selected column in ascending or descending manner accordingly.

### Actual behavior

Subscriptions not sorted the correct way.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes, 4392-gh-woocommerce/woocommerce-subscriptions.
- [x] Does this issue affect WooCommerce Payments? yes, https://github.com/Automattic/woocommerce-payments/issues/4573.

**Comment by mattallan** [comment]
I'm going to mark this one as low priority and blocking for now since it's not possible to fix this solely in Subscriptions and we'll need to make changes to WC Core to support sorting the HPOS orders query by a custom meta key.

In a WP POST environment, the way we sort these fields is by modifying the `WP_Query` query and setting the `orderby` to `'meta_value'` and then attaching `'meta_key' => '_meta_key_to_sort'` to the query.

In a HPOS environment, the `OrdersTableQuery` class doesn't support custom `orderby` fields and doesn't support ordering by a meta key and there are no filters to "hack" this approach.

**Comment by mattallan** [comment]
There's already an open issue for this in WC Core: https://github.com/woocommerce/woocommerce/issues/35486

**Comment by davefx** [comment]
https://github.com/woocommerce/woocommerce/issues/35486 was already fixed on January 13th.
