### ISSUE TITLE
With COT and syncing disabled, canceling/suspending a parent order does not cancel/suspend the subscription

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#202]
## Describe the bug

With Custom Order Tables and syncing disabled, updating the status of a parent order does not update the status of the related subscription.
In our `WC_Subscriptions_Manager` class we have a few functions hooked onto `woocommerce_order_status_{status}` hooks:

```
add_action( 'woocommerce_order_status_cancelled', __CLASS__ . '::cancel_subscriptions_for_order' );
add_action( 'woocommerce_order_status_failed', __CLASS__ . '::failed_subscription_sign_ups_for_order' );
add_action( 'woocommerce_order_status_on-hold', __CLASS__ . '::put_subscription_on_hold_for_order' );
```

I'm not sure which part of this flow is breaking the test but it could be either:
1. These hooks don't fire for COT orders
2. The `wcs_get_subscriptions_for_order()` isn't able to fetch the parent order from the related orders cache

I suspect it's option 2. that isn't working correctly, but we'll need to confirm.

## To Reproduce

1. Enable COT (using [this guide](https://github.com/Automattic/woocommerce/wiki/COT-Upgrade-Recipe-Book#how-to-enable-custom-order-tables))
2. Turn off posts table data syncing by going to **WooCommerce > Settings > Advanced > Custom data stores** and uncheck the "Keep the posts table and the orders tables synchronized" option
3. Purchase a new subscription via the checkout
4. Go to **WooCommerce > Orders** and visit the parent order of your new subscription
5. Change the status to cancelled
6. Go to **WooCommerce > Subscriptions** and confirm the subscription is still active

### Expected behavior

A subscription should be cancelled if the parent order is cancelled.

### Actual behavior

Subscription remains active

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes
- [x] Does this issue affect WooCommerce Payments? yes

**Comment by mattallan** [comment]
We have recently updated our `wcs_get_subscriptions_for_order()` which has likely fixed this issue. We'll need to confirm these on the latest `trunk` changes.

**Comment by shendy-a8c** [comment]
I confirm this issue cannot be reproduced in `trunk`. Closing...
