### ISSUE TITLE
One time shipping admin fields have broken markup

### ISSUE THREAD

**Issue by helgatheviking** [Automattic/woocommerce-subscriptions-core#203]
## Describe the bug
The [shipping fields close a div and then leave a new one opened but unclosed](https://github.com/Automattic/woocommerce-subscriptions-core/blob/c383a591f7686991615593475247ee5dfd935cdd/includes/admin/class-wc-subscriptions-admin.php#L389-L390).

This can have unintended consequences on other plugins that are attaching fields on the `woocommerce_product_options_shipping` hook. Basically if they don't mimic your markup pattern then the admin page can have broken markup.

As of WC 6.0 woo has added the [`woocommerce_product_options_shipping_product_data` filter](https://github.com/woocommerce/woocommerce/blob/3611d4643791bad87a0d3e6e73e031bb80447417/plugins/woocommerce/includes/admin/meta-boxes/views/html-product-data-shipping.php#L66) outside of the `<div class="options_group">`

This hook is generally better since you can properly open and close div elements which is more reliable for other extensions.

**Comment by Jinksi** [comment]
Just to confirm, is this issue the same as WooCommerce Subscriptions 4206-gh-woocommerce/woocommerce-subscriptions ?

**Comment by helgatheviking** [comment]
Yes. It's the same as https://github.com/woocommerce/woocommerce-subscriptions/issues/4206 i think the relevant code has since been split off to this repo.
