### ISSUE TITLE
Replace _post hooks

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#221]
## Describe the bug

There are a number of places in the code that hook into the `post` actions. These methods will not work with [HPOS](https://developer.woocommerce.com/2022/09/14/high-performance-order-storage-progress-report/) turned on and syncing to CPT turned off. There is already an issue to [Replace 'save_post' hooks](https://github.com/Automattic/woocommerce-subscriptions-core/issues/220) but there are other hooks we will need to replace such as `before_delete_post` `wp_trash_post` `deleted_post` `trashed_post`

A sample "find in files" regex search: `'(\w+)_post'`

Examples:
https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wc-subscriptions-checkout.php#L92
https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wc-subscriptions-manager.php#L51
https://github.com/Automattic/woocommerce-subscriptions-core/blob/3c7ae3489cacd2bf29ea59daf8702c8a914aafc8/includes/class-wc-subscriptions-manager.php#L57

**Comment by mattallan** [comment]
Thanks Bruce for opening this issue.

There are a few of these in the `WCS_Post_Meta_Cache_Manager` class as well but I've opened a separate issue to tackle that class as a whole: https://github.com/Automattic/woocommerce-subscriptions-core/issues/194


I wonder if there are CRUD-type replacement hooks we can replace these with that will work for Subscriptions stored in both Posts or Order Tables, or whether we have to surround these hooks with a `if (HPOS is not enabled); do _post hooks` condition 🤔

**Comment by mattallan** [comment]
Some details about these delete/trash hooks in slack: p1659617204621119-slack-C9QDV4TL4

Question raised:
> I'm trying to find replacements for wp_trash_post and delete_post which according to here (p1659338216364519-slack-C9QDV4TL4) should be `woocommerce_trash_order` or woocommerce_delete_order. However there are a few things that differ with those hooks. Firstly they are triggered after the order is deleted / trashed in the DB, the WP hooks fire before being deleted in the DB. Secondly those hooks are only called when WC_Order->delete is called. It doesn't trigger when we delete/trash a post in the dashboard. Also since we only get passed the order ID, our previous solution would read the order from DB before handling (which no longer works because the hooks get called after deleting from DB). What would be the recommended way to handle that?

Answer:

> you are right these hooks are fired after. We will add new hooks for compatibility `woocommerce_before_trash_order` and `woocommerce_before_delete_order` respectively.
>
> they still won't be fired when an order is trashed from the dashboard, since that request is completely handled by WordPress. so you would need to hook into both of these.
>
> I think we can hook into these filters ourselves and fire `woocommerce_*` hooks
>
> That way you would only need to hook into the  woo ones

Based on this conversation in slack, it sounds like there are direct replacements for these hooks but will also need to have the old `_post` hooks to support older versions of WC.

---

We'll need to confirm which WC version they made the `woocommerce_*` hooks also fire the post-related hooks but given this, I think our code will look something like this:

```
if ( wc pre 7.0 ) { 
    // call wp post hooks/filters
} else {
    // call new woocommerce_ hooks/filters
}
```
