### ISSUE TITLE
[HPOS] The billing address index field is duplicated in subscription meta

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-subscriptions-core#248]
## Describe the bug

On a store with HPOS tables enabled with no sync (this may also impact stores with syncing on) the billing address index is duplicated in the `wp_wc_orders_meta` table.

eg:

<img width="699" alt="Screen Shot 2022-11-07 at 10 09 40 am" src="https://user-images.githubusercontent.com/8490476/200203146-d4092704-1eea-41b6-b61b-b2487d8f5083.png">

## To Reproduce

1. Turn on HPOS and disable syncing. See screenshot below of HPOS settings below.
2. Purchase a subscription using BACs. 
3. In the database look at the `wp_wc_orders_meta` meta and notice the subscription has two billing index fields. 

<img width="769" alt="Screen Shot 2022-11-07 at 10 13 46 am" src="https://user-images.githubusercontent.com/8490476/200203381-c44b3a38-86f5-4ed4-a621-795eed19c2bd.png">

### Expected behavior

There should only be 1 billing index. 

### Actual behavior

There are 2 billing indexes and one of them is incomplete.

**Comment by Jinksi** [comment]
I haven't been able to reproduce this as per the steps in the description @james-allan:

After purchasing a sub with BACS, I see a single `_billing_address_index` on the order row, and 1 on the subscription row. 

<img width="816" alt="image" src="https://user-images.githubusercontent.com/3147296/200234069-f8fcc3ad-4dcc-48a0-b6fc-db6da0261f56.png">

One thing to note is that the non-HPOS behaviour sets the `_billing_address_index` value as the billing address on both sub & order, whereas now we're seeing an email address as the value on the subscription row.

**Comment by james-allan** [comment]
> I haven't been able to reproduce this as per the steps in the description @james-allan 

Hm strange. I've just replicated it again. I'll have to look into it again tomorrow to see I can see where my extra billing index is coming from.

> One thing to note is that the non-HPOS behaviour sets the _billing_address_index value as the billing address on both sub & order, whereas now we're seeing an email address as the value on the subscription row.

That should have been fixed with https://github.com/Automattic/woocommerce-subscriptions-core/pull/228.

**Comment by james-allan** [comment]
It appears to be related to [this `wcs_get_subscription()`](https://github.com/automattic/woocommerce-subscriptions-core/blob/2.5.1/wcs-functions.php#L193). 

I suspect what is happening is the index is being set to just the email on the `save()` [here](https://github.com/automattic/woocommerce-subscriptions-core/blob/2.5.1/wcs-functions.php#L184). That's because when you call `WC_Order::save()` WC core makes sure that the order has a billing email by copying it from the customer's user data.

Immediately after the `save()` in `wcs_create_subscription()` the subscription doesn't actually have any billing address index meta even though it would have been set. Later in the checkout flow, we copy the address data but because the subscription object didn't have the index meta, it sets another one. 🤔  

I'll have to look into this some more.

**Comment by james-allan** [comment]
It looks like this might be a bug in WC core. 

The following snippet causes duplicate billing indexes. 

```php
$order = wc_get_order( 297 );

echo $order->get_meta( '_billing_address_index' ); // <- Empty

$order->set_billing_first_name( 'bob' );
$order->save();

echo $order->get_meta( '_billing_address_index' ); // <- bob Allan  100 Main Rd  Brisbane QLD 4000 AU james.allan@automattic.com 0400000000
```

If I check the db the order now has 2 billing indexes, the original one and one with Bob as the first name. 

<img width="667" alt="Screen Shot 2022-11-07 at 10 04 08 pm" src="https://user-images.githubusercontent.com/8490476/200305945-b908a3a3-c10a-4626-8c6a-e83c0bbde54b.png">

**Comment by james-allan** [comment]
I've confirmed this was a known issue with WC core. They have since patched it in https://github.com/woocommerce/woocommerce/pull/35192. We should use the latest nightly build to get this fix.
