### ISSUE TITLE
[HPOS] Update wcs_do_subscriptions_exist() to support subscriptions stored in different data stores

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#251]
## Description

Our `wcs_do_subscriptions_exist()` runs a direct DB query on wp_posts table to determine if subscriptions exist on this store.
This DB query won't work when a store turns on HPOS without data syncing enabled.

To fix this, we should move these direct DB queries to happen in our datastore classes. Here's one way we could approach this:
 - [ ] Create a new function `do_subscription_exists()` in both of our data store classes `WCS_Orders_Table_Subscription_Data_Store` and `WCS_Subscription_Data_Store_CPT` these functions will query the proper databases
 - [ ] Update our `wcs_do_subscriptions_exist()` to call `WC_Data_Store::load( 'subscription' )->do_subscriptions_exist()`

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this feature affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by haszari** [comment]
I implemented one of these methods with [`wcs_get_orders`](https://github.com/woocommerce/woocommerce/blob/c27565f413a2bd19d24afbc8255f89444a06e1eb/plugins/woocommerce/includes/wc-order-functions.php#L28), i.e. using the current supported CRUD api for querying order-like data.

Code looks like this:

```php
public function do_subscriptions_exist() {
	$subscriptions_exist = false;
	$results             = wc_get_orders(
		array(
			'type'  => 'shop_subscription',
			'limit' => 1,
		)
	);
	$subscriptions_exist = count( $results ) > 0;
	return $subscriptions_exist;
}
```

@mattallan Is there a reason this wouldn't work for both order stores? Maybe we don't need a custom method in each data store.

**Comment by haszari** [comment]
Draft PR here: 

- https://github.com/Automattic/woocommerce-subscriptions-core/pull/273

I suspect this is worth merging, but I can imagine there are other scenarios where we might need datastore-specific versions. I'm keen to understand those scenarios.

**Comment by mattallan** [comment]
> Is there a reason this wouldn't work for both order stores?

@haszari My initial impression is that using `wc_get_orders()` should be perfectly fine. One thing we'll need to consider with this change is that `wc_get_orders()` is filterable by third parties and possibly a minor performance hit (not 100% sure on this). I don't see these being big issues but good to be mindful of and maybe worth a discussion on the PR 🤔 

One other small nit-pick is by default `wc_get_orders()` returns objects which we don't care about and is a hit to performance, so we should probably also set a `'return' => 'ids'` in the args, see [this wiki](https://github.com/woocommerce/woocommerce/wiki/wc_get_orders-and-WC_Order_Query).
