### ISSUE TITLE
Highlight subscriptions with missed payments in admin and/or notify merchant for subscriptions that failed renewal payment

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-subscriptions-core#260]
## Description

When a subscription doesn't renew on time there could be a number of causes - some of them may be critical in nature and cause loses for the merchant. 

- For tokenized subscriptions with WC Subscriptions the scheduled action queue that processes renewal payment jobs could be blocked or running behind schedule. 
- For WCPay (Stripe Billing) subscriptions there could be a sync issue where the subscription in Stripe is on-hold (paused) but the WC subscription is active. Stripe think the subscription is paused and so don't raise a charge request. 

No matter the circumstance there is currently no notification or alert system to let merchants know that something might have gone awry.

For a merchant to become aware, they would need to rely on their customers to notify them or for them to notice the subscription with a payment date in the past.  

<img width="1743" alt="Screen Shot 2022-11-14 at 3 52 55 pm" src="https://user-images.githubusercontent.com/8490476/201586045-56a93beb-795d-40e1-93f2-b593064cca2d.png">

_This screenshot was taken on August 2 and so these payments were missed 3 weeks earlier_

### Acceptance criteria 
- The merchant should be notified if there are active subscription on their store which have payment dates in the past by some period of time and therefore have been missed. 

### Additional context

This issue was filed under the broader context of improving the experience for merchants, HEs and ourselves when trying to troubleshoot scenarios where WC Pay subscriptions become inexplicably paused ( pbUcTB-162-p2#comment-4685 ). This is one of many possible issues that would improve the experience. 

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions? yes
- [x] Does this feature affect WooCommerce Payments? yes

**Comment by haszari** [comment]
This could be a notification (e.g. a notice or inbox message or even an email), or it could also be a UI improvement to the subscription list screen and/or subscription detail screen.

Here are some changes we could make to the list view:

- Show a different or additional status, e.g. ~~`Active`~~ `Missed Payment`. This might be complex as this is a new status or a change to the subscription status system. Could be an additional column.
- Add a label or other highlight to the `Next Payment` column if it's in the past (or other issue). A crude implementation would highlight the payment date in red; nicer would be a payment status label next to the payment date, e.g. `3 renewal payments missed`.
- Allow merchants to filter the list to show "unhealthy" subscriptions (e.g. missed recent renewal payment). This could work in combination with one of the row changes above.

FYI @james-allan I generalised the title, feel free to tweak it to clarify further.

**Comment by haszari** [comment]
I've started looking into this. I'll leave comments with where I get to, if anyone wants to take this over when I'm AFK – go for it :)

**Comment by haszari** [comment]
Here's a mockup showing `Payment overdue!` in red in the `Next payment date` column. This would be quick to ship & low risk IMO - just one idea :) 

<img width="1978" alt="Screenshot 2022-12-21 at 2 31 56 PM" src="https://user-images.githubusercontent.com/4167300/208799481-f53d20e7-f313-451e-9e78-98fe51d520a7.png">

Code on #354

**Comment by haszari** [comment]
Here's a mockup using a custom status for subscriptions that are behind on payments. Would be more complex to implement, but might be a more robust solution. For example, would be visible in edit subscription screen, and available via standard status APIs.

<img width="1124" alt="Overdue status" src="https://user-images.githubusercontent.com/4167300/209043281-d922b417-79fe-43e9-9b78-32d29ba96702.png">

We should also consider if we want to show something in the customer / my subscriptions screen. i.e. inform the subscriber that their subscription is not paid up to date.

**Comment by haszari** [comment]
> Here's a mockup using a custom status for subscriptions that are behind on payments. Would be more complex to implement, but might be a more robust solution. For example, would be visible in edit subscription screen, and available via standard status APIs.

After discussion offline between design & engineering (@james-allan @elizaan36), there's agreement that a custom `Overdue` status is likely a better approach. This accurately represents the status of the subscription to all parties.

We'll need to take care with this status and how it's communicated in the UI, as the payment be overdue for different reasons:

- Very slightly overdue due to timing of scheduled actions. 
- Actually overdue because payment failed. 

Next steps:

- Explore this technically & scope/prototype what work would be needed for `Overdue` status, including all affected modules/screens.
- Design mockups for affected flows. @elizaan36 is this something your team can fit in?

**Comment by elizaan36** [comment]
@haszari I can take a look at this next week.

**Comment by haszari** [comment]
> a custom Overdue status is likely a better approach.

> Design mockups for affected flows.

> I can take a look at this next week.

FYI @elizaan36 there's no urgency on those designs as we don't have bandwidth for a mini-project to add a new status right now. That said, this might be a useful consideration for future work in Subscriptions.

**Comment by haszari** [comment]
Updated design ideas from @elizaan36 for subtly highlighting overdue payments in the list view:

![Frame 13220](https://user-images.githubusercontent.com/4167300/213281721-05bd22c1-8c31-4e75-90e6-1d52f19b7643.png)

Will update #354 to match, and we can look at shipping that to help merchants detect overdue subs (catch issue after it happens) alongside more logging/order notes (to help diagnose root cause/interaction).
