### ISSUE TITLE
[HPOS] With data syncing enabled every subscription fetch is causing a sync

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-subscriptions-core#268]
## Describe the bug

When you have HPOS tables and syncing enabled (see screenshot below). Everytime you call `wcs_get_subscription` a sync request is fired off even if things are in sync. 
 
<img width="758" alt="Screen Shot 2022-11-16 at 3 59 14 pm" src="https://user-images.githubusercontent.com/8490476/202096275-63d4aed4-ad14-402a-9cf1-475a7ee95557.png">

## To Reproduce

1. Apply the settings above.
2. Trigger any `wcs_get_subscription()` call. 
    - either view the my account view subscription page
    - using wp console call `wcs_get_subscriptions()`. 
5. Inside the `maybe_sync_order` function add a breakpoint, error log or something to let you know the `migrate_post_record()` function is being called.

You'll notice that a simple fetch subscription request is causing the post record to be synced erroneously. 

### Expected behavior

The `migrate_post_record` should only be called if things are out of sync between the HPOS & posts tables.

### Actual behavior

From the debugging I've done, I discovered that the reason for this is because `is_post_different_from_order()` returns true when the subscription is being read. 

The reason for that is because the subscription record and the subscription post record are out of date with the following diff https://www.diffchecker.com/XvgpvNvF. Notice the `schedule_start`, `schedule_next_payment`, `requires_manual_renewal`, `suspension_count`, `billing_interval` & `billing_period` are all empty in the order record but populated in the post record.

The reason for that is because of the way we set those properties. They get set on the subscription in `set_subscription_props` and that function is called from the `read_multiple` function. However this post sync check happens in the `parent::read_multiple()` and so us setting these props after the parent function is called, is too late. [code ref](https://github.com/automattic/woocommerce-subscriptions-core/blob/5.0.0/includes/data-stores/class-wcs-orders-table-subscription-data-store.php#L362-L365). 

**Can't we then call `set_subscription_props` before `parent::read_multiple()` ?**

No we can't because in the `parent::read_multiple()` function they call `init_order_record()` and in that function they `$order->set_defaults();` which sets all the subscription props to empty, they call all these other functions like `init_meta_data()` but pass filtered meta (so our dates and billing interval meta will be excluded), they call `set_order_props_from_data()` but that only sets core order data from the HPOS orders, addresses, operational database tables (our keys are in meta). And all these functions are private and so we can't override them. 

I'm not sure how we're going to fix this. We might need to reach out to Proton. 

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by haszari** [comment]
@james-allan is this issue a blocker for subscriptions (WC Subscriptions or WCPay Subscriptions) supporting HPOS?

- Does it break a flow, i.e. this is a functional blocker?
- Otherwise, is it a blocker because it's a significant performance issue?

FYI @mattallan  – I'd assumed we'd need to scope this in upcoming sprint because it's important. Keen to confirm _why_ it's important (e.g. broken flow, architecture issue, performance issue/optimisation) so we can decide when to tackle this (soon or later).

**Comment by james-allan** [comment]
> is this issue a blocker for subscriptions (WC Subscriptions or WCPay Subscriptions) supporting HPOS?

No, as far as I can tell it's not actively blocking any flow. It may be a slight performance hit but my main concern is that the fix requires a change to WC core and so patching it early means we won't have a version compatibility juggle in the future, and because this area of the WC order datastore is complex. Resyncing order/subscription data from post records, when it's not necessary everytime we call `wcs_get_subscription()` somewhat scares me because of how fundamental getting a subscription object is and how likely it is that this resyncing code could go haywire.

**Comment by haszari** [comment]
Thanks for the explanation @james-allan ! Makes sense to me, let's target getting this wrapped up in next sprint.
