### ISSUE TITLE
[HPOS] Edit Subscription admin screen: Trying to get property 'ID' of non-object 

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#299]
## Describe the bug

A php notice is thrown on the edit subscription admin screen.

```
Notice: Trying to get property 'ID' of non-object in
woocommerce/src/Internal/Utilities/COTMigrationUtil.php on line 99
```

## To Reproduce

1. With HPOS enabled and set as the default order storage, edit a subscription in /wp-admin/
2. See the error in the Schedule metabox.

![image](https://user-images.githubusercontent.com/57298/203445964-a11e0029-9031-498a-8802-b05af2cbff59.png)

**Comment by brucealdridge** [comment]
This is caused by https://github.com/woocommerce/woocommerce/issues/35543 - added `blocked` label.
Unrelated to subscriptions-core, will leave this issue open until it is resolved in WC.

**Comment by james-allan** [comment]
We could fix this on our end by circumventing the flow that leads WC to calling `get_post_or_object_meta()` by passing an actual value instead of relying on WC to fetch it for us.

**Comment by webdados** [comment]
I can confirm this happens also when editing an order and HPOS is activated
