### ISSUE TITLE
[HPOS] List Subscriptions admin screen: Uncaught exception during bulk update subscription status

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#301]
## Describe the bug

When doing a bulk update of subscription status from the subscriptions list admin screen an uncaught exception is thrown.

```
Fatal error: Uncaught Exception: Unable to change subscription status to "processing". 
in woocommerce-subscriptions-core/includes/class-wc-subscription.php:433 

Stack trace: 
#0 woocommerce/src/Internal/Admin/Orders/ListTable.php(1145): WC_Subscription->update_status('processing', 'Order status ch...', true) 
#1 woocommerce/src/Internal/Admin/Orders/ListTable.php(1068): Automattic\WooCommerce\Internal\Admin\Orders\ListTable->do_bulk_action_mark_orders(Array, 'processing') 
#2 woocommerce/src/Internal/Admin/Orders/PageController.php(238): Automattic\WooCommerce\Internal\Admin\Orders\ListTable->handle_bulk_actions() 
#3 woocommerce/src/Internal/Admin/Orders/PageController.php(122): Automattic\WooCommerce\Internal\Admin\Orders\PageController->setup_action_list_orders() 
#4 [internal function]: Automattic\WooCommerce in woocommerce-subscriptions-core/includes/class-wc-subscription.php on line 433
```

![image](https://user-images.githubusercontent.com/57298/203447421-038b1e2b-40ac-44b6-a885-4b62e495d087.png)

## To Reproduce

1. With HPOS enabled and set as the default order storage, click on the subscriptions menu item in wp-admin.
2. Select one or more subscriptions and update the status.
3. See error
![image](https://user-images.githubusercontent.com/57298/203447472-5f03a2a3-e24e-4a5f-b376-d688a1947187.png)

**Comment by james-allan** [comment]
I've indicated on #367 that this issue is also fixed by the changes in that PR. I wasn't able to replicate on that branch but also suspect that this was fixed by another earlier change as "processing" isn't a valid action to take on a subscription.
