### ISSUE TITLE
Add support to WCS_Object_Data_Cache_Manager to handle when orders/subscriptions are trashed, deleted and untrashed

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-subscriptions-core#310]
**🛑 Blocked by**

- https://github.com/Automattic/woocommerce-subscriptions-core/issues/221

## Describe the bug

In #304 I introduced new `WCS_Object_Data_Cache_Manager_Many_To_One` & `WCS_Object_Data_Cache_Manager` to handle when orders/subscriptions are updated, however the child class also has hooks to handle when the related object is trashed, deleted and untrashed. 

https://github.com/Automattic/woocommerce-subscriptions-core/blob/121ef4b833aa9ae47e91e22389fca8d30057deba/includes/class-wcs-post-meta-cache-manager.php#L39-L42

In #304 I wasn't able to add support for those flows because those hooks aren't yet resolved for subscriptions on HPOS sites.

Once #221 is resolved, we will need to update the `WCS_Object_Data_Cache_Manager` class to make sure we're taking care of objects (orders and subscriptions) when they are deleted, trashed or untrashed and that the cache is updated appropriately. 

### To test

1. Set up your site with HPOS tables enabled. 
2. Trash, delete and untrash orders and subscriptions and make sure the appropriate caches are updated.
    - When deleting, trashing or untrashing a **subscription** - the user's subscription cache (`_wcs_subscription_ids_cache` usermeta) should update accordingly
    - When trashing, deleting or untrashing **orders** - the related subscription's related order caches should be updated accordingly based on the order type and relationship.

### Developer notes

I had a look into what hooks we have available and there are a few things:

1. We can use the `woocommerce_before_delete_order` hook. However there is currently no subscription equivalent. 
2. For trashing we can use `woocommerce_subscription_trashed` or `woocommerce_trash_order`  - the fact these two hooks aren't the same format is annoying but we can work with that. eg just hook on both formats. 
3. `woocommerce_untrash_order` for untrashing orders, there isn't currently a subscription equivalent.

**Comment by shendy-a8c** [comment]
~Could this have been fixed by https://github.com/Automattic/woocommerce-subscriptions-core/pull/350?~ nope.
