### ISSUE TITLE
[HPOS] Viewing Subscriptions admin screen, filters are missing with HPOS enabled. 

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#323]
## Describe the bug

With HPOS enabled and using [HPOS Admin UI support](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) and associated [WooCommerce PR](https://github.com/woocommerce/woocommerce/pull/35658) there are custom filters that are not showing.

**CPT**
![Screenshot 2022-11-29 at 1 59 36 PM](https://user-images.githubusercontent.com/57298/204412644-f9857c59-57cd-44ec-949a-2fc6d05093d5.png "CPT ListTable screen showing filters")
**HPOS**
![Screenshot 2022-11-29 at 2 00 56 PM](https://user-images.githubusercontent.com/57298/204412653-37094cad-8338-409f-b407-0963b2d492a0.png "HPOS ListTable screen showing filters")

Blocked/Resolved by: https://github.com/woocommerce/woocommerce/issues/35753

## To Reproduce

1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. See the filters are missing for Product and Payment method.

**Comment by mattallan** [comment]
Fixed by #332
