### ISSUE TITLE
Add support for php8.2

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#325]
## Description

There are a number of features that are being deprecated in php 8.2 and then removed in php9 that we need to resolve.
Full detail of [php8.2 changes](https://stitcher.io/blog/new-in-php-82)

#### Deprecation of dynamic properties [RFC](https://wiki.php.net/rfc/deprecate_dynamic_properties)

Anywhere that class variables are used without being explicitly set (`__get` and `__set` will continue to work) will now generate a Deprecation warning.

https://github.com/Automattic/woocommerce-subscriptions-core/blob/d08ed6617ad73fb8dc3dd16bce23a4817ae5c78c/includes/legacy/class-wc-product-subscription-legacy.php#L39-L41

In this example, `setting_id` is not defined and will generate a warning.

#### Deprecation of `${}` string interpolation [RFC](https://wiki.php.net/rfc/deprecate_dollar_brace_string_interpolation)

Usage of `${}` is now deprecated inside strings will now generate a Deprecation warning.

I can only find one instance of this which should be okay as this is **not** inside a string
https://github.com/Automattic/woocommerce-subscriptions-core/blob/d08ed6617ad73fb8dc3dd16bce23a4817ae5c78c/includes/class-wcs-cart-renewal.php#L1171

#### Deprecation of partially supported callables [RFC](https://wiki.php.net/rfc/deprecate_partially_supported_callables)

The following callable types are now deprecated
```
"self::method"
"parent::method"
"static::method"
["self", "method"]
["parent", "method"]
["static", "method"]
["Foo", "Bar::method"]
[new Foo, "Bar::method"]
```

They can be replaced using the following pattern.
```
"self::method"       -> self::class . "::method"
"parent::method"     -> parent::class . "::method"
"static::method"     -> static::class . "::method"
["self", "method"]   -> [self::class, "method"]
["parent", "method"] -> [parent::class, "method"]
["static", "method"] -> [static::class, "method"]
```

I couldn't find any examples of usage in the codebase where updates will be required but further testing will be needed.

### Testing instructions

Run smoke tests and unit tests with php8.2 installed.

related to #324

**Comment by bummytime** [comment]
Bumping this → I saw a few of these warnings in wp-admin after updating WooPayments:

```
Deprecated: Creation of dynamic property WCS_Email_Completed_Renewal_Order::$heading_downloadable is deprecated in /srv/users/user8a0d7d3c/apps/user8a0d7d3c/public/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/emails/class-wcs-email-completed-renewal-order.php on line 38

Deprecated: Creation of dynamic property WCS_Email_Completed_Renewal_Order::$subject_downloadable is deprecated in /srv/users/user8a0d7d3c/apps/user8a0d7d3c/public/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/emails/class-wcs-email-completed-renewal-order.php on line 40

Deprecated: Creation of dynamic property WCS_Email_Completed_Switch_Order::$heading_downloadable is deprecated in /srv/users/user8a0d7d3c/apps/user8a0d7d3c/public/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/emails/class-wcs-email-completed-switch-order.php on line 38

Deprecated: Creation of dynamic property WCS_Email_Completed_Switch_Order::$subject_downloadable is deprecated in /srv/users/user8a0d7d3c/apps/user8a0d7d3c/public/wp-content/plugins/woocommerce-payments/vendor/woocommerce/subscriptions-core/includes/emails/class-wcs-email-completed-switch-order.php on line 39
```

cc @diegocurbelo @mattallan @james-allan
