### ISSUE TITLE
Show Subs-core version in SSR.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#328]
## Description

Especially when testing WCS vs WCPay and potentially developing on subscriptions-core it can be difficult to know what version of the subscriptions-core library is being loaded.

Adding the version of the subscriptions-core library to the SSR will help find the library version both in development and when debugging issues for merchants.

### Testing instructions

1. Go to WooCommerce -> Status
2. Scroll down to 'Subscriptions'
3. Expect to see 'Subscriptions Core Library Version'

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions? yes
- [x] Does this feature affect WooCommerce Payments? yes

**Comment by haszari** [comment]
Nice idea @brucealdridge !
