### ISSUE TITLE
[HPOS] Admin can't filter subscriptions list when HPOS is enabled.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#334]
## Describe the bug

Using the filters on the Subscriptions listing in wp-admin does not work.

![image](https://user-images.githubusercontent.com/57298/205539305-02fd807a-36ea-4a6a-abd0-5b811b9852a8.png)

## To Reproduce

With the #332 pull-request checked out.
1. With HPOS enabled, Go to 'Subscriptions' in wp-admin.
2. Filter by payment method, customer or product
3. See that the filtering doesn't happen.

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by mattallan** [comment]
I've assigned myself this issue as I'm also looking at #200 and filtering and sorting the subscriptions list are handled by the same function so I'll tackle it in one.
