### ISSUE TITLE
[HPOS] Subscriptions metabox shows below order items in admin screens.

### ISSUE THREAD

**Issue by brucealdridge** [Automattic/woocommerce-subscriptions-core#338]
## Describe the bug

When viewing a subscription in wp-admin with HPOS enabled the subscription details show below the order details. The expected order of information presented is the details of the subscription (Customer, Billing & Shipping Address) followed by the order details.

## To Reproduce

1. With the [`hpos-admin-ui-support`](https://github.com/Automattic/woocommerce-subscriptions-core/pull/297) branch checked out.
2. Click on Subscriptions in wp-admin.
3. Select a subscription to view (or create a new subscription)
4. See the incorrect order.

### Expected behavior

![image](https://user-images.githubusercontent.com/57298/205758688-c15c2f15-9777-40ce-aab3-a606ab456a71.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/57298/205758577-2d4b8196-f371-4636-bd43-8bf60d1def54.png)

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by mattallan** [comment]
I'm going to attach a `low:priority` to this one as it's not breaking on HPOS, just more a QOL change that we should look into later.

There's some more details shared in slack that will help when we tackle this. See thread: p1670446463081999-slack-C03SKBVPQ78
