### ISSUE TITLE
Cannot re-subscribe to a variable subscription properly

### ISSUE THREAD

**Issue by webthread** [Automattic/woocommerce-subscriptions-core#423]
## Describe the bug
1. User signs up for a variable subscription
2. Subscription lapses or is cancelled
3. User wants to sign up to a different variation of that subscription, not possible as the only option is to resubscribe to the previous variation of the subscription. You have manually delete the cancelled subscription/s to allow them to select one of the variations on the subscription.
4. This message is also incorrectly displayed "You have already subscribed to this product and it is limited to one per customer. You can not purchase the product again." This shows whether or not limit purchases to 1 item per order is selected.

### Expected behavior
Once a variable subscription lapses, you should be able to sign up for any of the other variations of that product, not just the previously purchased one.

### Actual behavior
You can only resubscribe to the previous variable, no variations are shown on the product page

## Product impact
WooCommerce Subscriptions > Variable subscriptions

**Comment by csmcneill** [comment]
Howdy @webthread! Is the [Limit subscription functionality](https://woocommerce.com/document/subscriptions/store-manager-guide/#limit-subscription) at **Product data > Advanced** set to `One of any status` for the "Full Membership" product in the image you shared?

**Comment by webthread** [comment]
Hi @csmcneill I'm so sorry you are 100% correct. The only bug is my ability to go through the settings carefully... please delete or close this issue.
