### ISSUE TITLE
A user with role: -No role for this site- becomes Admin after signing up for a sub

### ISSUE THREAD

**Issue by jacoswan** [Automattic/woocommerce-subscriptions-core#463]
## Describe the bug

WordPress has various user roles, one of which is `- No role for this site -`. When that is set, if the user buys a Subscription product, their user role is changed to Adminstrator. 

## To Reproduce

1. Go to Users > All Users
2. Edit a random user and change their Role to `- No role for this site -`
3. Update user
4. On the front end, purchase a Subscription product (test with simple, $10/month sub) and complete checkout
5. After the order is complete, the user is now an Administrator

### Expected behavior

When purchasing a non-subscription product, the role is left as is. So signing up for a subscription should either be the same as that, or at minimum switch the role to Subscriber, but certainly not Administrator. 

### Actual behavior

User role is switched to Administrator with all the trappings. 

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

## Additional context

Stumbled upon while looking for default features with which to block an existing user from making purchases. While this ultimately didn't work, the outcome was concerning.

**Comment by james-allan** [comment]
Hi @jacoswan. 

I haven't been able to replicate this issue. When I change one of my user's role to `'No role for this site'`

<img width="500" alt="Screenshot 2023-07-07 at 3 19 03 pm" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/5d49ac01-f6a9-45b3-bece-6e0881602dda">

and I make a subscription purchase, the user's role is set to "Subscriber" not administrator

<img width="500" alt="Screenshot 2023-07-07 at 3 21 52 pm" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/d08764bb-b773-4e77-b6a3-26f7684687fe">

Could you double check your **WooCommerce > Settings > Subscriptions** to make sure you haven't inadvertently set the subscriber role to "Administrator".

<img width="600" alt="Screenshot 2023-07-07 at 3 26 38 pm" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/8490476/d3e5d9fa-0c8f-480b-bb7e-133b25608764">

**Comment by jacoswan** [comment]
Hi @james-allan, thanks for checking. 

How embarrassing for me, that's exactly the reason 🤦🏻‍♂️ I can't explain how that would have happened (and more importantly, why I didn't check that before opening this issue). 

Sorry for wasting your time.
