### ISSUE TITLE
Orders List Table doesn't show the subscription custom columns when HPOS is enabled

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#469]
## Describe the bug

On stores with HPOS enabled, the Orders List table no longer shows the custom "Subscription Relationship" columns:

![image](https://github.com/Automattic/woocommerce-subscriptions-core/assets/2275145/609bb416-6d5f-4157-99dc-ffbefcb0a0d0)

In our [WC_Subscriptions_Order](https://github.com/Automattic/woocommerce-subscriptions-core/blob/24db3cf51eb191edb21e79421387072194b59046/includes/class-wc-subscriptions-order.php#L31-L33) class we are hooking onto `manage_edit-shop_order_columns` and `manage_shop_order_posts_custom_column` hooks to add these custom columns, but these only work in non-HPOS environments.

For HPOS we need to use the following hooks:

- `manage_woocommerce_page_wc-orders_columns`
- `manage_woocommerce_page_wc-orders_custom_column`

## To Reproduce

1. Enable HPOS
2. Purchase a subscription product and process a renewal
3. Visit the **WooCommerce > Orders** table and note that there's no columns for subscription relationships

## Product impact

- [ ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ ] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by EjayhanFernandes** [comment]
Initially reported here: 6532020-zen
