### ISSUE TITLE
Issue creating variable subscription products with WooCommerce 7.9.0

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#475]
## Describe the bug

With WooCommerce 7.9.0, when you try to create a new variable subscription product, the "Used for variations" checkbox is disabled on the Product Attributes metabox which prevents the attributes from being used to later create variations:

![image](https://github.com/Automattic/woocommerce-subscriptions-core/assets/2275145/72cd06b0-f434-4c81-aac6-eefdb7e66c17)

Relevant changes in WooCommerce that caused this:
- [WooCommerce PR #38802](https://github.com/woocommerce/woocommerce/pull/38802) Changed the Used for variations checkbox code and adds a new enable_if_variable className
- [WooCommerce PR #39106](https://github.com/woocommerce/woocommerce/pull/39106) Causes the Used for variations checkbox to be disabled for variable subscription products

## To Reproduce

1. Install the latest WooCommerce 7.9.0
2. Go to Products > Add New
3. Choose "Variable Subscription"
4. On the Attributes tab, notice the "Used for variations" checkbox is checked but disabled.
5. Upon adding attributes and pressing update, the "Used for variations" checkbox is hidden
6. Go to Variations tab and you will not be able to add any variations for the attributes you added previously.

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [x] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by thuautp** [comment]
reported in 6549344-zen. I suggested them to downgrade to WC 7.8.2 until fix is released

**Comment by kaushikasomaiya** [comment]
@mattallan @james-allan I am seeing a strange behaviour also noted in 6566198-zen

On creating a variable subs product - it works fine however on pressing update button repeatedly without touching anything on the product data part - the "Used for variations" in attribute is unchecked automatically.

Video: https://d.pr/v/ZCtaOt

**Comment by kaushikasomaiya** [comment]
Created an issue here: https://github.com/Automattic/woocommerce-subscriptions-core/issues/480
