### ISSUE TITLE
Use admin theme colors, instead of hardcoded ones

### ISSUE THREAD

**Issue by PanosSynetos** [Automattic/woocommerce-subscriptions-core#490]
While working on 
- pdqkbG-2Tq-p2#comment-1471
- https://github.com/woocommerce/woocommerce/pull/39182

I noticed that Subscriptions is introducing a "pink" icon with hardcoded color, on the Payments Settings page.

![image](https://github.com/Automattic/woocommerce-subscriptions-core/assets/2484390/eca38060-2836-4680-8b4a-e8c7236745f6)

This icon color is at
- https://github.com/Automattic/woocommerce-subscriptions-core/blob/507720f600363a6c1e7da1b4b82660c7ab6a0c0e/assets/css/admin.css#L738C10-L738C16

But there are more places with hardcoded pink colors, here's a list of all different pinks in the CSS files
- `#9c5d90`
- `#a46497`
- `#cc99c2`
- `#b366a4`
- `#bb77ae`
- `#aa559a`

I'd recommend these colors to change to `var(--wp-admin-theme-color)` or `var(--wp-admin-theme-color-darker-10)`

The color changes introduced in PR woocommerce/woocommerce/pull/39182 will be released in WC 8.1

**Comment by samnajian** [comment]
See more context pdqkbG-2Tq-p2#comment-1439
