### ISSUE TITLE
Subscription renewal failure - WCS_Related_Order_Store_Cached_CPT::add_relation()

### ISSUE THREAD

**Issue by robm92** [Automattic/woocommerce-subscriptions-core#494]
## Describe the bug

We are getting numerous failed subscription renewal scheduled actions on the dashboard, all with the same error:

failed to finish processing due to the following exception: Argument 1 passed to WCS_Related_Order_Store_Cached_CPT::add_relation() must be an instance of WC_Order, bool given, called in /home/{site name}/public_html/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/wcs-renewal-functions.php on line 36

## Product impact
Woocommerce Subscriptions plugin

- [ ] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? yes

**Comment by solstudioim** [comment]
Found something similar in this ticket: 6507998-zd-a8c

**Comment by robm92** [comment]
Any update on this? Do you have a link to the ticket or is it internal?

**Comment by WillBrubaker** [comment]
I've got one of these, the fatal is happening right after a database deadlock in that case. #6553698-zen
