### ISSUE TITLE
[HPOS]: Missing compatibility for `orders_by_type_query` filter box in order listing screen.

### ISSUE THREAD

**Issue by vedanshujain** [Automattic/woocommerce-subscriptions-core#496]
## Description

When HPOS is active, looks like we don't show the order type filter box on the admin order list screen. Basically, [these two functions needs to also use the HPOS hooks](https://github.com/Automattic/woocommerce-subscriptions-core/blob/trunk/includes/class-wc-subscriptions-order.php#L708-L805) so we display these filter boxes when HPOS is active. I think we can use the `woocommerce_order_list_table_restrict_manage_orders` to hook `restrict_manage_subscriptions` and then perhaps hook the `orders_by_type_query` to `woocommerce_order_list_table_prepare_items_query_args`.

### Testing instructions

1. Set HPOS to authoritative.
2. Go to orders admin list view.
3. See that orders type filter box is not present.

## Product impact

- [x] Does this feature affect WooCommerce Subscriptions?
- [ ] Does this feature affect WooCommerce Payments?

**Comment by MariaChek** [comment]
We had a report about this in 6788276-zen. Do we have any estimation about when we'll look into this? Thanks!

**Comment by a-danae** [comment]
Hey @MariaChek! The fix for this was just merged. It should be included in the upcoming versions of WooCommerce Subscriptions.
