### ISSUE TITLE
Switching proration not working as the documentation is understood

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-subscriptions-core#524]
## Describe the bug

Maybe this can be thought of as a double switch. After an initial purchase of a subscription and a subsequent downgrade, and then an upgrade, the pro-rated switch price seems incorrect.

## To Reproduce

1. Prorate for upgrades and downgrades of all subscription products
2. Subscription length is never prorated
3. Never prorate the sign up fee.
4. A subscription has weekly, monthly, and yearly variations. Each are $1 for their period.
5. Purchase the monthly variation.
6. Switch to the yearly variation ($0 due at checkout)
7. Switch to the weekly variation. $1 due at checkout.

### Expected behavior

[Upgrades](https://woocommerce.com/document/subscriptions/switching-guide/#section-12) indicates to me that there should not be a gap payment collected.

### Actual behavior

There's a charge for something I feel I've already paid for but not received.

## Product impact

- [yes ] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ no] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

## Additional context

7149492-zen

**Comment by james-allan** [comment]
Issue transferred to the subscriptions plugin repo. `subscriptions-core` doesn't contain subscription switching feature code. 

See https://github.com/woocommerce/woocommerce-subscriptions/issues/4568
