### ISSUE TITLE
Unexpected behavior when paying for failed renewal order

### ISSUE THREAD

**Issue by WillBrubaker** [Automattic/woocommerce-subscriptions-core#530]
## Describe the bug

When using a coupon during the checkout process for a failed renewal order, a new order is generated and it is detached from the subscription that the renewal order originally belonged to.

## To Reproduce

1. A percentage coupon code exists for 25% off
2. A subscription exists
3. Do whatever is necessary to ensure the renewal payment will fail
4. Use the "Pay" link to pay for the renewal - noting the order ID you're paying for.
5. During the checkout process, apply the coupon from step 1 and complete checkout.
6. Note that the order ID shown on the TYP is not the same as the order ID you noted in step 4
7. Also note that there is now an orphaned subscription order.

### Expected behavior

I'm not entirely sure. I'm guessing though that since not all gateways support recurring amount changes, I expect a new subscription to be created, and the order I just paid for to be attached to that subscription. 

Perhaps coincidentally in ticket ID 7131510-zen a new subscription is created. My belief is that this is the correct behavior.

In any case, I'd expect clear subscription/order notes to indicate why new orders/subscriptions are created.

## Product impact

- [ yes] Does this issue affect WooCommerce Subscriptions? yes/no/tbc, add issue ref
- [ no] Does this issue affect WooCommerce Payments? yes/no/tbc, add issue ref

**Comment by james-allan** [comment]
Hey @WillBrubaker Thanks for filing the issue. :) 

Were you using a block checkout by any chance during this? We patched this very issue in https://github.com/Automattic/woocommerce-subscriptions-core/pull/498 which will go out in the next release. 

Following your steps, I wasn't able to reproduce on the standard shortcode checkout or the block checkout.

> Expected behavior - I'm not entirely sure. 

Paying for failed renewals orders should always resume payment of the original order and always be linked to the original subscription. It should never result in a new order or new subscription. If you add coupons during checkout, then it just updates the order totals and items.

**Comment by WillBrubaker** [comment]
Yeah, I must have been using the block checkout. Thanks.
