### ISSUE TITLE
Updating subscription via API sets start_date to now

### ISSUE THREAD

**Issue by snnx** [Automattic/woocommerce-subscriptions-core#542]
## Describe the bug
If I push an update to a subscription via the API, it changes start_date to the current time.

## To Reproduce

With an existing subscription

Run cURL command (as per https://woocommerce.github.io/subscriptions-rest-api-docs/#update-a-subscription)

```
curl -X PUT https://example.om/wp-json/wc/v3/subscriptions/123456 \
    -u consumer_key:consumer_secret \
    -H "Content-Type: application/json" \
    -d '{
  "next_payment_date": "2023-12-06 12:47:01"
}'
```

Check out subscription in admin and start_date has changed:

<img width="317" alt="CleanShot 2023-11-14 at 15 42 55" src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/45337114/62576664-8621-4cda-8ab2-9136751279af">

### Expected behavior

Shouldn't change start_date if you are just editing a subscription

### Actual behavior

Updates start_date to current time

## Product impact

* Does this issue affect WooCommerce Subscriptions? yes
* Does this issue affect WooCommerce Payments? tbc

## Additional context

Possible solution is to add $creating as below to start_date if statement within method `prepare_object_for_database` in `class-wc-rest-subscriptions-controller.php`, as when not creating and not setting the start_date in cURL json above, then the start_date is reset to now.

```
if ( $creating && ! isset( $request['start_date'] ) ) {
	$request['start_date'] = gmdate( 'Y-m-d H:i:s' );
}
```

**Comment by bryceadams** [comment]
+1 Confirmed this bug on 5.7.0.
