### ISSUE TITLE
Subscription table is empty in mobile view.

### ISSUE THREAD

**Issue by Mayisha** [Automattic/woocommerce-subscriptions-core#584]
## Describe the bug
With HPOS enabled, the subscription table is empty in mobile view. 
Issue reported in p1711127516765309-slack-C7U3Y3VMY.

## To Reproduce

- Create a test site.
- Install WooCommerce `8.7.0` and Woo Subscriptions `6.0.0`.
- Enable HPOS.
- Create at least one subscription.
- Go to the Subscriptions page at `/wp-admin/admin.php?page=wc-orders--shop_subscription`.
- Notice that the subscription is present in the table.
- Now inspect at a mobile breakpoint (max-width: 782 px). Notice that the table is empty.

<img src="https://github.com/Automattic/woocommerce-subscriptions-core/assets/33387139/acab1157-7664-4be6-a9e3-c8d9f7d9beb5" width="50%" height="50%" />

### Expected behavior
- The list of subscriptions should load in the mobile view as well.

**Comment by JoshuaGoode** [comment]
There are other styles and elements missing as well on both desktop and mobile, this one is just the most noticeable.

For example, the WooCommerce admin bar that appears immediately below the WP-Admin bar is completely missing on this HPOS version of the page.
