### ISSUE TITLE
Update Subscriptions Core to include the fixes in the latest Subscriptions Extension 3.1.6

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#6]
### Description
In WooCommerce Subscriptions 3.1.6, we reverted a commit which introduced a bug where the "limit subscription" advanced setting was no longer showing on Simple Subscription Products.

Because Subscriptions Core was built off Subscriptions 4.0, which was built off 3.1.5, we'll need to manually cherry-pick this commit to WCS Core until Subscriptions 4.0 is merged into `woocommerce-subscriptions/trunk`.

Here's the changes to be merged into core: 4214-gh-woocommerce/woocommerce-subscriptions

### Steps to replicate

1. Have WooCommerce Subscriptions Core installed as a standalone plugin (requires WC Payments on `feature/stripe-billing` or WC Subscriptions extensions `4-0-bleeding` branches being active)
2. While on WCS Core trunk, go into **Products > Add New**
3. Set the product type to Simple Subscription
4. Notice there's no "limit subscription" setting under the Advanced tab

![](https://d.pr/i/qQPiuK+)

**Comment by haszari** [comment]
@james-allan should we include this in MVP scope? I'm assuming yes, and might a `Size S` that's easy to pick up 👍

**Comment by james-allan** [comment]
Yep, we will want to do an update of core before we release WCPay Subscriptions. I'd suggest we do it somewhat last minute (end of next week or very early in the following week) unless there's a specific reason to do it earlier - just so we don't have to do it multiple times if there are last-minute changes to Subscriptions.

**Comment by mattallan** [comment]
Closing as this has already been done: https://github.com/Automattic/woocommerce-subscriptions-core/commit/8465217e20736e8d60121593a0ee9c69729ae9e6
