### ISSUE TITLE
Uncaught exception 'TypeError' with message 'WCS_Related_Order_Store_Cached_CPT::delete_relations

### ISSUE THREAD

**Issue by manzurahammed** [Automattic/woocommerce-subscriptions-core#600]
## Describe the bug

Found this fatal error in our store.

Uncaught exception 'TypeError' with message 'WCS_Related_Order_Store_Cached_CPT::delete_relations(): Argument #1 ($order) must be of type WC_Order, bool given, called in /var/www/wp-content/plugins/woocommerce-subscriptions/includes/switching/class-wc-subscriptions-switcher.php on line 791' in /var/www/wp-content/plugins/woocommerce-subscriptions/vendor/woocommerce/subscriptions-core/includes/data-stores/class-wcs-related-order-store-cached-cpt.php:189

## Product impact
Woocommerce Subscriptions plugin

- [ ] Does this issue affect WooCommerce Subscriptions? yes
- [ ] Does this issue affect WooCommerce Payments? yes

**Comment by james-allan** [comment]
> [!note] 
> `WCS_Related_Order_Store_Cached_CPT::delete_relations()` is only currently called in 1 place ([code link](https://github.com/woocommerce/woocommerce-subscriptions/blob/6.1.0/includes/switching/class-wc-subscriptions-switcher.php#L786)) and it just passes the result of `wc_get_order()` so I think we will just need to be more defensive there.

**Comment by mattallan** [comment]
Closed by 4648-gh-woocommerce/woocommerce-subscriptions
