### ISSUE TITLE
"Subscription updated." message is not showing whenever do any update in the subscription from admin panel.

### ISSUE THREAD

**Issue by TechAhead20** [Automattic/woocommerce-subscriptions-core#613]
**Describe the bug**
The "Subscription updated." message is not showing whenever do any update in the subscription from the admin panel.

**To Reproduce**
Go to any subscription edition page from the backend and update the subscription using the "Update" button. The subscription gets updated but no update message shows when HPOS is enabled.

**Expected behavior**
The "Subscription updated." message should be showing.

**Suggesstion**
**_woocommerce_order_updated_messages_** filter hook should be using instead of **_post_updated_messages_** when HPOS is enabled.

**Comment by davefx** [comment]
Fixed by #615

**Comment by mattallan** [comment]
Thanks @TechAhead20 and @davefx
