### ISSUE TITLE
Migrating Unit Tests: Admin, Coupons and Gateways unit tests

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#63]
Working on this issue will rely on the unit test helpers being migrated: #60
Related to woocommerce/woocommerce-subscriptions#4195

---

## Description

The goal of this issue is to migrate coupon, gateway, and admin related unit tests from the WC Subscriptions repository to the list of Subscriptions Core unit tests.

The unit test files that need to be migrated from `woocommerce-subscriptions` include:
 - [x] `tests/unit/admin/admin-post-types.php`
 - [ ] `tests/coupons/coupons.php`
   - not including any `WCS_Limited_Recurring_Coupon_Manager` tests as thats a feature of WC Subscriptions)
- [x] [`tests/unit/admin/wcs-permalink-manager.php`](https://github.com/woocommerce/woocommerce-subscriptions/blob/ee34132a5e49a2de3360c1a3e20def46d17165fc/tests/unit/admin/wcs-permalink-manager.php) should be moved out of `tests/unit/admin` and put in `tests/unit/` 
- [ ] `tests/unit/gateways/wcs-test-subscriptions-payment-gateways.php`
  - this class was split into a core and pro version so some of these tests won't need to be migrated over

As part of migrating these tests over, we should also:
 - [x] use consistent naming of test files i.e. test-{file-name}.php
 - [x] each test class should extend `WP_UnitTestCase` instead of `WCS_Unit_Test_Class`
 - [x] keep the `subscriptions-core/tests/unit/` file structure the same as `subscriptions-core/includes` (i.e. the coupons test file doesn't need to be in its own directory)

**Comment by james-allan** [comment]
Both `tests/coupons/coupons.php` and `tests/unit/gateways/wcs-test-subscriptions-payment-gateways.php` shouldn't be moved for a couple of reasons. 

The `coupons.php` test file includes 4 tests. [2 are testing](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/tests/unit/coupons/coupons.php#L73-L148) limited coupon functionality which is a plugin feature. [The other 2](https://github.com/woocommerce/woocommerce-subscriptions/blob/trunk/tests/unit/coupons/coupons.php#L43-L64) aren't actually testing any functionality they are simply testing if creating a coupon using a unit test helper function returns a coupon with the given type. I think those 2 tests could just be deleted - they aren't really testing anything. 

The `wcs-test-subscriptions-payment-gateways.php` test file includes 1 test which tests the `WC_Subscriptions_Payment_Gateways::trigger_gateway_renewal_payment_hook` function. That function is the plugin function responsible for triggering payment gateway payment hooks, doesn't exist in subscriptions-core and therefore should remain in the Subscriptions plugin unit tests.
