### ISSUE TITLE
Migrating Unit Tests: Subscriptions, emails & other files

### ISSUE THREAD

**Issue by mattallan** [Automattic/woocommerce-subscriptions-core#64]
Working on this issue will rely on the unit test helpers being migrated first: #60
Related to woocommerce/woocommerce-subscriptions#4195

---

## Description

This issue is to track migrating the existing unit tests found on WC Subscriptions repository that are related to the main WC Subscription class, emails and other remaining unit tests like the core autoloader.

Test files that will need to be migrated over include:
- [x] `tests/unit/subscriptions/subscriptions.php`
- [x] `tests/unit/subscriptions/subscriptions-payment-count.php`
  - this is testing `subscription->get_payment_count()` and doesn't need to be a separate class so it should be moved into the above file
- [x] `tests/unit/wcs_emails.php`
- [x] `tests/unit/wcs_post_meta_cache_manager.php`
- [x] `tests/unit/wcs_test_autoloader.php`

As part of moving these files over, we should also:

- [x] use consistent naming convention i.e. `test-{file-name}.php`
- [x] each test class should extend `WP_UnitTestCase` instead of `WCS_Unit_Test_Class`
- [x] keep the `tests/unit/` file structure similar to that of `subscriptions-core/includes`. Rather than having `unit/subscriptions` this should go in `tests/unit/test-{file-name}.php`

**Comment by brucealdridge** [comment]
The following files I already ported as part of #61 and are not included in this PR
`tests/unit/wcs_post_meta_cache_manager.php`
`tests/unit/wcs_test_autoloader.php`

I've kept `tests/unit/subscriptions/subscriptions.php` & `tests/unit/subscriptions/subscriptions-payment-count.php` as separate files as the subscriptions test file is already a little overwhelming and easier to manage with it split up.
