### ISSUE TITLE
Move Welcome message after installing/activating from Core to Subscriptions pro 

### ISSUE THREAD

**Issue by leonardola** [Automattic/woocommerce-subscriptions-core#8]
Remove this message from core and port it to Subscriptions pro

<img width="1183" alt="135557328-536501a7-73b2-4b1c-8d51-2ebaed860d3b" src="https://user-images.githubusercontent.com/6342964/137370065-54a6f09e-ba99-458c-993d-90c7c80a4006.png">

This is displayed when WCPay is active and WCPay Subscriptions is enabled (via wp option `_wcpay_feature_subscriptions`).

Should be worker alongside with https://github.com/Automattic/woocommerce-payments/issues/3024  and https://github.com/woocommerce/woocommerce-subscriptions/issues/4226

### To Reproduce
1. Install WC Pay, get subscriptions active. 
2. Activate WC Pay subscriptions using WC Pay DEV
3. See admin notice in plugins screen and possibly elsewhere in admin.

### Expected behavior
Each plugin extending Subscriptions core should implement it's own way of showing a welcome message. The core should not have a default message.

The existing message should be ported to Subscriptions pro through [#4226](https://github.com/woocommerce/woocommerce-subscriptions/issues/4226)

**Comment by haszari** [comment]
Closing this – the plan is to move the notice from subs core (library) into Subscriptions extension. See this issue for details: 

- https://github.com/Automattic/woocommerce-payments/issues/3024#issuecomment-940571808

**Comment by leonardola** [comment]
@haszari but we need to remove it from the core first don't we? I am coping the code to the subscriptions pro

**Comment by haszari** [comment]
> but we need to remove it from the core first don't we? I am coping the code to the subscriptions pro

Yep for sure - sounds like you have it under control, I was expecting that we'd do the remove and the add in separate PRs at the same time so it's clear what's happening, or there would be an issue opened to ensure it gets added to back to pro extension.

Either way we don't want an issue for removing - that's misleading, as it's not the outcome we want 😀. The other issue #4226 looks 👌  - thank you !

**Comment by leonardola** [comment]
I've updated the description here as it was misleading and I am reopening this issue as it will be closed by #11
