### ISSUE TITLE
Fatal errors thrown on the admin Subscriptions table when a subscription doesn't load

### ISSUE THREAD

**Issue by james-allan** [Automattic/woocommerce-subscriptions-core#83]
#### ❗ This issue relates to the WC Subscriptions issue: 4286-gh-woocommerce/woocommerce-subscriptions

When `wcs_get_subscription` returns `false` for some reason, the subsequent code to render the admin subscription table doesn't handle this well, e.g. `render_shop_subscription_columns` function calls `$the_subscription->get_status()` without checking the function is actually getting a subscription or `output_rows` is calling` $subscription->get_parent_id()`, again without checking if it's actually not getting `false` instead of the subscription object.

This causes a fatal.

## To Reproduce

1. With a subscription with corrupt data (for example an invalid next payment data meta - [like a string](https://user-images.githubusercontent.com/8490476/148148478-30691cb0-e408-403c-98b4-4768dbe83623.png)), view the admin subscriptions table. 

 
### Expected behavior

No errors.

### Actual behavior

Fatal errors

<img width="820" alt="Screen Shot 2022-01-05 at 12 04 38 pm" src="https://user-images.githubusercontent.com/8490476/148159531-5a753f42-be65-4142-8815-92140f2c19f2.png">

## Product impact

- [x] Does this issue affect WooCommerce Subscriptions?
   - 4286-gh-woocommerce/woocommerce-subscriptions
- [x] Does this issue affect WooCommerce Payments? 
    - https://github.com/Automattic/woocommerce-payments/issues/3596

**Comment by shendy-a8c** [comment]
@james-allan should this issue be closed now that https://github.com/Automattic/woocommerce-subscriptions-core/pull/84 has been merged?

**Comment by james-allan** [comment]
yep. :) 

Thanks @shendy-a8c
